### ISSUE TITLE
Duplicates created in CRM but no indication in the code/logs

### ISSUE THREAD

**Issue by FlandersBurger** [AleksandrRogov/DynamicsWebApi#103]
When leads are created through the api, duplicates are created in CRM. There is no indication in the logs that the duplicates were created at all. I don't know where to look, everything seems to suggest only one was created until I look in CRM. I have confirmed the below code is only executed once.
Note that the forms are triplicated too

Code:
![image](https://user-images.githubusercontent.com/8195826/135550703-decd0f70-e1b3-46a1-bb20-a171bed31443.png)

Log:
![image](https://user-images.githubusercontent.com/8195826/135550834-ef558018-fd34-49b8-8ba0-21745235d476.png)

CRM Database
![image](https://user-images.githubusercontent.com/8195826/135550814-afdddf74-0700-4355-8726-dbc56b9f049c.png)

I was wondering if this could be set in the options of the confiugration:
https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/manage-duplicate-detection-create-update

**Comment by AleksandrRogov** [comment]
Hi @FlandersBurger ,
I don't really see DynamicsWebApi used here. Are you wrapping it in your class?
To be honest, I use my library in wide range of projects and never had an issue with the duplicates. I would suggest you to try and use the DynamicsWebApi object without a helper to see if the issue is indeed inside the library.

Let me know what you find.

**Comment by AleksandrRogov** [comment]
Also, I would suggest making your calls with `duplicateDetection = true` (if you don't do that already). I think, the duplicate detection is not getting executed by default.

```js
await dynamicsWebApi.createRequest({ collection: "leads", entity: lead, duplicateDetection: true });
```

**Comment by FlandersBurger** [comment]
> Also, I would suggest making your calls with `duplicateDetection = true` (if you don't do that already). I think, the duplicate detection is not getting executed by default.
> 
> ```js
> await dynamicsWebApi.createRequest({ collection: "leads", entity: lead, duplicateDetection: true });
> ```

Thanks, I'll try this and see what happens. The helper just points to dynamicsWebApi.create, I'll elaborate the code if duplicateDetection doesn't work! 

Thanks again.
