### ISSUE TITLE
Facing issue with Dynamics 365 online

### ISSUE THREAD

**Issue by maheshghori** [AleksandrRogov/DynamicsWebApi#11]
Hello AleksandrRogov,

Thanks for the library. This is indeed very useful. But after adding "dynamics-web-api" as a web resource to entity form and when I try initializing class object var dynamicsWebApi = new DynamicsWebApi(); like this, I am getting error that DynamicsWebApi is not found. Am I missing anything over here ? Your feedback will be really helpful.

Thanks,
Mahesh G

**Comment by AleksandrRogov** [comment]
Hi @maheshghori,
Where do you call an initialization: in a global scope or inside the function (local scope)? It's better not to initialize objects in a global scope in Dynamics 365.

Thanks

**Comment by maheshghori** [comment]
Hi @AleksandrRogov thanks for the quick response. Yes I was initializing it in a global scope. After I moved it to particular method call it works like a charm.

Thanks again 👍
