### ISSUE TITLE
Future Enhancement - countAll (RetrieveTotalRecordCount)

### ISSUE THREAD

**Issue by nabeelamir-defra** [AleksandrRogov/DynamicsWebApi#113]
I saw in this package there is a workaround to count all records in a collection. The method
[RetrieveTotalRecordCount](https://stackoverflow.com/questions/51543802/counting-all-rows-in-dynamics-crm-online-web-api-odata) can be used instead. The request looks something like this
https://<your api url>/RetrieveTotalRecordCount(EntityNames=['accounts'])

**Comment by AleksandrRogov** [comment]
@nabeelamir-defra thank you! is it a new one? I did not know it was there. I will implement this for sure!

**Comment by nabeelamir-defra** [comment]
I think it has been there since 2019, but I only just spotted it now!

**Comment by AleksandrRogov** [comment]
I have decided that I am not going to implement this, because the returned data is from a 24h snapshot, thus, the count that will be retrieved is not up to date (which is a breaking change). 
Also this calculation can be simply executed with `executeFunction` function if needed:
```js
const result = await dynamicsWebApi.executeFunction("RetrieveTotalRecordCount", { EntityNames: ["account"] });
```
