### ISSUE TITLE
oDataNextLink examples

### ISSUE THREAD

**Issue by pixelpaulaus** [AleksandrRogov/DynamicsWebApi#114]
Hello,
Just wondering if you have any examples of using oDataNextLink returned values to fetch the next lot of records?

**Comment by AleksandrRogov** [comment]
@pixelpaulaus there's the 2nd parameter in `retrieveMultipleRequest` where you pass the `oDataNextLink` to retrieve the next page. 
Here's a page from the [Wiki](https://github.com/AleksandrRogov/DynamicsWebApi/wiki/api-classes-dynamicswebapi#retrievemultiplerequest-1) 

So it should be something like this:

```js

//set the request parameters
const request = {
    collection: "leads",
    select: ["fullname", "subject"],
    filter: "statecode eq 0",
    maxPageSize: 5,
    count: true
};

//perform a multiple records retrieve operation
dynamicsWebApi.retrieveMultipleRequest(request).then(function (response) {

    const count = response.oDataCount;
    const nextLink = response.oDataNextLink;
    const records = response.value;
    
    return dynamicsWebApi.retrieveMultipleRequest(request, nextLink);
}).then(function(response) {
   //page 2
}).catch(function (error){
    //catch an error
});

```

**Comment by AleksandrRogov** [comment]
Closing this.
