### ISSUE TITLE
I feel like the intention here is to use `replaceAll` rather than `replace`

### ISSUE THREAD

**Issue by m1c43L** [AleksandrRogov/DynamicsWebApi#117]
https://github.com/AleksandrRogov/DynamicsWebApi/blob/2866b41da48d38ff33683b9b3eed3cff82977bab/lib/helpers/ErrorHelper.js#L145

This is cause a buggy behavior when we are doing something like ``key=${JSON.stringify(value)}``. It would only replace one of the double quote to single quote causing the line below it to throw.

**Comment by AleksandrRogov** [comment]
@m1c43L true.

**Comment by AleksandrRogov** [comment]
going to replace it with a regular expression
