### ISSUE TITLE
Fetching CSDL metadata document

### ISSUE THREAD

**Issue by whyvez** [AleksandrRogov/DynamicsWebApi#12]
Is there any way to fetch the CSDL metadata document using this library? Is there any way to send a raw http request instead of using the API's defined in the readme?

**Comment by AleksandrRogov** [comment]
Hi @whyvez ,
Unfortunately, it's not possible at this moment.

Do you think it's a good idea to add a function that can be used to send a raw http request to Web API? If yes, I can try to implement it asap, I guess you need to have an access to request headers, a request url and a request body. Let me know if you need to set anything else.

Thank you.

**Comment by whyvez** [comment]
@AleksandrRogov I can send you a PR if you want... Would be glad to help as we will be using your this module in a project of ours.

**Comment by AleksandrRogov** [comment]
Hi @whyvez ,
Sure! I appreciate your help.

**Comment by dhepper** [comment]
Hi, I'm also trying to fetch some metadata and I think sending a raw request would be the easiest way. May I ask if anyone of you has worked on this? Otherwise I will give it a shot.

**Comment by AleksandrRogov** [comment]
Hi @dhepper ,
I have not worked on it. If you can help us to do that it would be great. And let me know if you have any issue with the code.
Thanks

**Comment by dhepper** [comment]
Thanks for the quick reply @AleksandrRogov. I'll send a PR once I have something working. I think I'll get to it next week.

**Comment by ncjones** [comment]
Was there a resolution for this? Any hints how I can use the API to discover all available entities and describe the properties on the entities?

**Comment by ncjones** [comment]
The solution to my problem was in the readme but it was hard to find because of the terminology used to describe the operations.

List available entity types:

```javascript
client.retrieveEntities(['LogicalName'], "OwnershipType eq Microsoft.Dynamics.CRM.OwnershipTypes'UserOwned'")
  .then(response => response.value.map(entity => entity.LogicalName))
  .then(names => names.join('\n'))
  .then(console.log)
```

Describe entity:

```javascript
client.retrieveAttributes(`LogicalName='${entityName}'`)
  .then(response => response.value.map(attribute => attribute.LogicalName))
  .then(names => names.join('\n'))
  .then(console.log)
```

In the readme these operations are described as "Retrieve Multiple Entities" and "Retrieve Multiple Attributes" respectively. Maybe it's just my lack of familiarity with the Dynamics terminology but those descriptions are not intuitive to me.

**Comment by AleksandrRogov** [comment]
Hi @ncjones ,
I am glad you found a solution. If I add a "metadata" keyword will that be more intuitive? For example: "Retrieve Entity Metadata", "Retrieve Metadata of Multiple Entities".
