### ISSUE TITLE
Requesting / posting using alternate keys

### ISSUE THREAD

**Issue by killi3000** [AleksandrRogov/DynamicsWebApi#14]
Is there a way to make requests using alternate keys?

http://www.oak3.org/crm/using-alternate-keys-webapi/

**Comment by AleksandrRogov** [comment]
Hi @killi3000 ,
At this moment, there is no such functionality. I will work on adding it as soon as possible.

Thank you for letting me know about this missing feature.

**Comment by killi3000** [comment]
Thank you! Looking forward to get this function also

Mvh
Henrik Killi

18. nov. 2017 5:49 p.m. skrev "Aleksandr Rogov" <notifications@github.com>:

**Comment by AleksandrRogov** [comment]
Hi Henrik,

I've just release a new version, where I add this feature. Please refer to readme or check the following examples:

Simple request:
```js
var alternateKey = "key='keyValue'"; 
//or var alternateKey = "key='keyValue',anotherKey='keyValue2'";

//perform a retrieve operaion
dynamicsWebApi.retrieve(alternateKey, "leads", ["fullname", "subject"]).then(function (record) {
    //do something with a record here
})
.catch(function (error) {
    //catch an error
});
```

Advanced request:

```js
var request = {
    key: "alternateKey='keyValue'",
    collection: 'leads',
    select: ['fullname', 'subject']
};

dynamicsWebApi.retrieveRequest(request).then(function (record) {
    //do something with a record
})
.catch(function (error) {
    //if the record has not been found the error will be thrown
});
```

You can use `key` as a primary key (instead of `id`).

Please let me know if you encounter any issue with it.

Best Regards,

**Comment by killi3000** [comment]
Awesome! Thank you:)
