### ISSUE TITLE
Creating Tables and columns dynamically

### ISSUE THREAD

**Issue by sriharikrishna33** [AleksandrRogov/DynamicsWebApi#140]
Dear @AleksandrRogov

Is there any way to create tables and columns dynamically?

**Comment by AleksandrRogov** [comment]
@sriharikrishna33 yes. please use functions related to [Entity Metadata](https://github.com/AleksandrRogov/DynamicsWebApi#work-with-metadata-definitions).

Official documentation: https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/use-web-api-metadata

My documentation uses Dataverse SDK terminology btw where Entity = Table and Attribute = Column.
https://learn.microsoft.com/en-us/power-apps/developer/data-platform/understand-terminology#terminology-use-depending-on-protocol-or-technology

**Comment by sriharikrishna33** [comment]
@AleksandrRogov 

Thank you and please provide a sample example of how we can achieve using nodejs.

**Comment by AleksandrRogov** [comment]
@sriharikrishna33 there are examples in a README file I linked you to.

**Comment by AleksandrRogov** [comment]
Closing this issue. If there are more questions please feel free to add a comment even if it's closed.
