### ISSUE TITLE
Allow custom headers to be passed to the request

### ISSUE THREAD

**Issue by dnns6** [AleksandrRogov/DynamicsWebApi#151]
Situation: I have a legacy Dynamics 365 (on prem) instance with a custom authentication. I can bypass that auth with specific http-headers (Coookies to be precise)

Request: Allow custom headers to be passed via the DynamicsWebApi config object which are added to each request. (Alternative: in the request object for each request... slightly more effort for me, but it would work)

Thanks for considering :-)
And thanks for the solution!!

**Comment by AleksandrRogov** [comment]
Implemented in v.2.1.0.
