### ISSUE TITLE
Use failure (this is not a bug)

### ISSUE THREAD

**Issue by rickeygong** [AleksandrRogov/DynamicsWebApi#159]
**DynamicsWebApi version**
For example: v2.1

**Describe the bug**
this is not a bug

**Expected behavior**
Couldn't get user id.

**Actual result**
'Hello Dynamics 365! My id is: undefined'

**Code Snippet**
```js
if (typeof (Dealer) == "undefined") {
    Dealer = { __namespace: true };
}
Dealer = {
    _executionContext: null,
    _formContext: null,
    _lookupsupplierId: null,
    OnLoad: function (executionContext) {
        executionContext = executionContext;
        _formContext = executionContext.getFormContext();
        
    },
    SayHello: function(){
        //By default DynamicsWebApi makes calls to 
        //Web API v9.2 and Search API v1.0
        const dynamicsWebApi = new DynamicsWebApi();
        const response = dynamicsWebApi.callFunction("WhoAmI");
        Xrm.Navigation.openAlertDialog({ text: `Hello Dynamics 365! My id is: ${response.UserId}` });
    },
}
```

**Steps To Reproduce**
If there are additional steps that need to be done to reproduce the behavior, describe them here:
1. I put 'dynamics-web-api.js' in the dist folder onto the Dealer form.
2. Then I custom added a JS(code above) and registered it in the Dealer form , 
3. Call 'dealer.sayHello' when onload
4. After publishing the solution, refresh the form and pop up 'Hello Dynamics 365! My id is: undefined'

**Screenshots**
![image](https://github.com/AleksandrRogov/DynamicsWebApi/assets/51323554/6a571bc7-ed3b-45fb-a92c-f396cd3caef8)
![image](https://github.com/AleksandrRogov/DynamicsWebApi/assets/51323554/d30b9db7-10d4-4864-8c30-6afd622b9a07)

**Comment by AleksandrRogov** [comment]
hi @rickeygong . that's strange. going to try to reproduce it.
