### ISSUE TITLE
Pagination Issue

### ISSUE THREAD

**Issue by ArtashMardoyanS** [AleksandrRogov/DynamicsWebApi#164]
**DynamicsWebApi version**
For example: ^2.1.1

**Describe the bug**
'@odata.nextLink' when we use for the second parameter in "retrieveMultiple" function it returns an error

**Actual result**
The URI 'https://devsi.api.crm.dynamics.com/devsi.api.crm.dynamics.com/api/data/v9.2/contacts?$select=contactid&$count=true&$skiptoken=<cookie pagenumber="2" pagingcookie="%253ccookie%2520page%253d%25221%2522%253e%253ccontactid%2520last%253d%2522%257b7A3921EA-A4BC-EA11-A812-000D3A33FB82%257d%2522%2520first%253d%2522%257bCADD76EA-09B0-EA11-A812-000D3A3155C1%257d%2522%2520%252f%253e%253c%252fcookie%253e" istracking="False" />?$select=contactid&$count=true' is not valid because it is not based on 'https://devsi.api.crm.dynamics.com/api/data/v9.2/'.

**Code Snippet**
```js
async retrieveContacts() {
        try {
            this.loggerService.trace(`[${this.constructor.name}.retrieveContacts]`);

            const request = {
                collection: 'contacts',
                select: ['contactid'],
                maxPageSize: 10,
                count: true
            };

            const firstPage = await this.dynamicsWebApi.retrieveMultiple(request);

            console.log(firstPage.value[0]);
            const nextPageLink = firstPage['@odata.nextLink'];

            console.log(nextPageLink);

            const secondPage = await this.dynamicsWebApi.retrieveMultiple(request, nextPageLink);

            console.log(secondPage.value[0]);

            return firstPage;
        } catch (ex) {
            this.loggerService.error(`[${this.constructor.name}.retrieveContacts]`, ex);
            throw new InternalServerErrorException(ex);
        }
    }
```

**Comment by AleksandrRogov** [comment]
@ArtashMardoyanS the error happens because count gets added to a request twice. Once with `nextPageLink` and another with `request.count`. A workaround for now, until I decide what to do with this:

```js
            const request = {
                collection: 'contacts',
                select: ['contactid'],
                maxPageSize: 10,
                count: true
            };

            const firstPage = await this.dynamicsWebApi.retrieveMultiple(request);

            console.log(firstPage.value[0]);
            const nextPageLink = firstPage['@odata.nextLink'];

            console.log(nextPageLink);

            const nextPagesRequest = {
                collection: request.collection,
                maxPageSize: request.maxPageSize,
            }

            const secondPage = await this.dynamicsWebApi.retrieveMultiple(nextPagesRequest , nextPageLink);
```

P.S. I was getting a different error when trying to execute your request though:

`'Query option '$count' was specified more than once, but it must be specified at most once.'`

**Comment by ArtashMardoyanS** [comment]
@AleksandrRogov thank you for your quick response.

Describe the bug
We changed our code and tried to get the next page like your solution but we again received an error.

Actual result
The URI 'https://devsi.api.crm.dynamics.com/devsi.api.crm.dynamics.com/api/data/v9.2/contacts?$select=contactid&$count=true&$skiptoken=<cookie pagenumber="2" pagingcookie="%253ccookie%2520page%253d%25221%2522%253e%253ccontactid%2520last%253d%2522%257b7A3921EA-A4BC-EA11-A812-000D3A33FB82%257d%2522%2520first%253d%2522%257bCADD76EA-09B0-EA11-A812-000D3A3155C1%257d%2522%2520%252f%253e%253c%252fcookie%253e" istracking="False" />' is not valid because it is not based on 'https://devsi.api.crm.dynamics.com/api/data/v9.2/'.

`
 async retrieveContacts() {
        try {
            this.loggerService.trace(`[${this.constructor.name}.retrieveContacts]`);

            const request = {
                collection: 'contacts',
                select: ['contactid'],
                maxPageSize: 10,
                count: true
            };

            const firstPage = await this.dynamicsWebApi.retrieveMultiple(request);

            console.log(firstPage.value[0]);
            const nextPageLink = firstPage['@odata.nextLink'];

            console.log(nextPageLink);

            //removing 'select' and 'count' from a request because they get duplicated in the result url
            const nextPagesRequest = {
                maxPageSize: request.maxPageSize,
                collection: request.collection
            };

            const secondPage = await this.dynamicsWebApi.retrieveMultiple(nextPagesRequest, nextPageLink);

            console.log(secondPage.value[0]);

            return firstPage;
        } catch (ex) {
            this.loggerService.error(`[${this.constructor.name}.retrieveContacts]`, ex);
            throw new InternalServerErrorException(ex);
        }
    }
`

**Comment by AleksandrRogov** [comment]
@ArtashMardoyanS what's your DynamicsWebApi config? specifically server url in there? I see that for some reason your serverUrl gets duplicated. At least that's what the error shows. You can see `https://devsi.api.crm.dynamics.com/devsi.api.crm.dynamics.com/` <- `devsi.api.crm.dynamics.com` in there twice.

**Comment by ArtashMardoyanS** [comment]
@AleksandrRogov Yes I also see this issue

My credentials
# DYNAMICS DB PARAMETERS
DYNAMICS_CLIENT_ID="***"
DYNAMICS_CLIENT_SECRET="***"
DYNAMICS_INSTANCE_URI="https://devsi.api.crm.dynamics.com/"
DYNAMICS_AUTHORITY_URL="https://login.microsoftonline.com/d0f7f33f-8d1f-4ac0-bccd-2ecda8bf422b"

`
import * as MSAL from '@azure/msal-node';
import { ConfigService } from '@nestjs/config';
import { DynamicsWebApi } from 'dynamics-web-api';
import { InternalServerErrorException, Injectable } from '@nestjs/common';

import { LoggerService } from '@app/shared/logger';

@Injectable()
export class DynamicsService {
    private dynamicsWebApi: DynamicsWebApi;

    constructor(
        private readonly loggerService: LoggerService,
        private readonly configService: ConfigService
    ) {
        this.initializeDynamicsWebApi();
    }

    private initializeDynamicsWebApi() {
        const clientId = this.configService.get<string>('DYNAMICS.CLIENT_ID');
        const instanceUri = this.configService.get<string>('DYNAMICS.INSTANCE_URI');
        const clientSecret = this.configService.get<string>('DYNAMICS.CLIENT_SECRET');
        const authorityUrl = this.configService.get<string>('DYNAMICS.AUTHORITY_URL');

        const msalConfig = {
            auth: {
                knownAuthorities: ['login.microsoftonline.com'],
                clientSecret: clientSecret,
                authority: authorityUrl,
                clientId: clientId
            }
        };

        const cca = new MSAL.ConfidentialClientApplication(msalConfig);

        this.dynamicsWebApi = new DynamicsWebApi({
            onTokenRefresh: async () => {
                try {
                    const result = await cca.acquireTokenByClientCredential({
                        scopes: [`${instanceUri}/.default`]
                    });

                    return result.accessToken;
                } catch (ex) {
                    this.loggerService.error(`[${this.constructor.name}.initializeDynamicsWebApi]`, ex);
                    return null;
                }
            },
            serverUrl: instanceUri
        });
    }

    async retrieveContacts() {
        try {
            this.loggerService.trace(`[${this.constructor.name}.retrieveContacts]`);

            const request = {
                collection: 'contacts',
                select: ['contactid'],
                maxPageSize: 10,
                count: true
            };

            const firstPage = await this.dynamicsWebApi.retrieveMultiple(request);

            console.log(firstPage.value[0]);
            const nextPageLink = firstPage['@odata.nextLink'];

            console.log(nextPageLink);

            //removing 'select' and 'count' from a request because they get duplicated in the result url
            const nextPagesRequest = {
                maxPageSize: request.maxPageSize,
                collection: request.collection
            };

            const secondPage = await this.dynamicsWebApi.retrieveMultiple(nextPagesRequest, nextPageLink);

            console.log(secondPage.value[0]);

            return firstPage;
        } catch (ex) {
            this.loggerService.error(`[${this.constructor.name}.retrieveContacts]`, ex);
            throw new InternalServerErrorException(ex);
        }
    }
}

`

**Comment by AleksandrRogov** [comment]
@ArtashMardoyanS and what value has `nextPageLink` when you first log it? (just to 100% be sure it's not the value that comes back from the Dataverse)

I will try to reproduce this locally.

**Comment by ArtashMardoyanS** [comment]
![Uploading Screenshot 2023-12-22 at 18.54.40.png…]()

**Comment by AleksandrRogov** [comment]
@ArtashMardoyanS please remove a slash "/" at the end of your `DYNAMICS_INSTANCE_URI` for now. That slash seems to cause an issue.

`DYNAMICS_INSTANCE_URI="https://devsi.api.crm.dynamics.com"`

I will work on the fixes. Thank you for submitting the bugs.

**Comment by AleksandrRogov** [comment]
@ArtashMardoyanS I fixed the issues in v.2.1.2. It can be downloaded from npm. If you have any issues with an update let me know. Thanks!

**Comment by ArtashMardoyanS** [comment]
@AleksandrRogov thanks, I'll check and let you know

**Comment by ArtashMardoyanS** [comment]
@AleksandrRogov We updated the version to "2.1.2" and now it is working thank you so much you helping us.
