### ISSUE TITLE
DynamicsWebApi is not a constructor

### ISSUE THREAD

**Issue by sya-sp** [AleksandrRogov/DynamicsWebApi#166]
**DynamicsWebApi version**
v2.1.1

**Describe the bug**
Not able to initialize constructor

**Actual result**
DynamicsWebApi is not a constructor

**Code Snippet**
```js
var DynamicsWebApi = require("dynamics-web-api")
var dynamicsWebApi = new DynamicsWebApi();
```

**Steps To Reproduce**
https://runkit.com/embed/dlxpjx6nnivz

**Your Setup (please complete the following information):**
 - Node v20.11.0
 - Dynamics 365 Online

**Comment by AleksandrRogov** [comment]
hi @sya-sp ,
I will need to figure out why this happens, looks like I may be missing some configuration in esbuild during compilation process. Need to dive into some CommonJS concepts. Please, for a CommonJS module use the following for now:

```js
var DynamicsWebApi = require("dynamics-web-api").DynamicsWebApi;

var dynamicsWebApi = new DynamicsWebApi();
```

Thank you

**Comment by AleksandrRogov** [comment]
I decided not to change this behavior, even though there are ways to achieve a single export. The main reasoning is: I don't want to introduce a breaking change. _Though I may change my mind in the future :)._

Thank you for reporting this.
