### ISSUE TITLE
Create record with lookup field

### ISSUE THREAD

**Issue by killi3000** [AleksandrRogov/DynamicsWebApi#17]
Is there a way to create a record with a lookup field? Something like:

//initialize a CRM entity record object
var lead = {
    _regardingobjectid_value: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    subject: "Test WebAPI",
    firstname: "Test",
    lastname: "WebAPI",
    jobtitle: "Title"
};
//call dynamicsWebApi.create function
dynamicsWebApi.create(lead, "leads").then(function (id) {
    //do something with id here
}).catch(function (error) {
    //catch error here
})

**Comment by AleksandrRogov** [comment]
Hi @killi3000 ,
In Web Api all "lookup" fields are read only, including `_regardingobjectid_value`. You need to use a navigation property to associate entities. Please check this [link](https://msdn.microsoft.com/en-us/library/gg328090.aspx#Associate%20entities%20on%20create) or [this link](http://www.inogic.com/blog/2016/02/set-values-of-all-data-types-using-web-api-in-dynamics-crm/).

**Comment by killi3000** [comment]
Thank you for your reply. Using the format above gives me this error message: 

"Invalid URI: The hostname could not be parsed"

**Comment by AleksandrRogov** [comment]
Where are you using DynamicsWebApi (in CRM or in Node.js app)?

**Comment by killi3000** [comment]
In node.js app

**Comment by AleksandrRogov** [comment]
Are you providing `webApiUrl` during initialization?
```js
var dynamicsWebApi = new DynamicsWebApi({webApiUrl: 'https:/myorg.api.crm.dynamics.com/api/data/v9.0/'});
```

**Comment by killi3000** [comment]
No. I tried this now, but this gave my a new error: 

Error: connect ECONNREFUSED 127.0.0.1:443
at Object._errnoException (util.js:1024:11)
at _exceptionWithHostPort (util.js:1046:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

**Comment by AleksandrRogov** [comment]
You need to acquire a token first.
Please follow this [example](https://github.com/AleksandrRogov/DynamicsWebApi#dynamicswebapi-for-nodejs).

**Comment by killi3000** [comment]
Ok. I will look into it tomorrow morning. Thanks for your help!

**Comment by killi3000** [comment]
I was a bit tired last evening, so I didn't think about it, but I was already providing the `WebApiUrl` and acquire a token. The code works fine if I delete the `'regardingobjectid_account@odata.bind': "/accounts(xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)",`

Does it matter that the entity I am trying to create is an activity?

**Comment by killi3000** [comment]
I figured it out! I had an `/` at the end of my `WebApiUrl`. This was causing the `Invalid URI` error. I removed the `/` from `'regardingobjectid_account@odata.bind': "/accounts(xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)"`

And now it works:)

**Comment by AleksandrRogov** [comment]
I am glad it's working for you and thanks for letting me know about that slash, I need to fix it.
