### ISSUE TITLE
Azure Dataverse Error:Xrm Context is not available - Azure Pipeline

### ISSUE THREAD

**Issue by rmeloni** [AleksandrRogov/DynamicsWebApi#172]
**DynamicsWebApi version**
"dynamics-web-api": "^2.1.4",

**Describe the bug**
Run a retrieveMultiple inside BDD pipeline Azure DevOps

[Nest] 2298  - 06/21/2024, 5:47:15 PM   ERROR [ExceptionsHandler] Azure Dataverse Error:Xrm Context is not available. In most cases, it can be resolved by adding a reference to a ClientGlobalContext.js.aspx. Please refer to MSDN documentation for more details.

Error: Azure Dataverse Error:Xrm Context is not available. In most cases, it can be resolved by adding a reference to a ClientGlobalContext.js.aspx. Please refer to MSDN documentation for more details.
    at AzureDataverseService.getTable (/home/vsts/work/1/s/Sistemas/MovimentosOffsites/API/src/azure-integration/services/azure-dataverse.service.ts:72:13)

**Expected behavior**
Don´t show this error message.

**Actual result**
Just an error or an end result.

**Code Snippet**
```js
const dynamicsAPI = new DynamicsWebApi({
    onTokenRefresh: acquireToken,
    serverUrl: environment.dataverse.serverUrl,
  });

const response = await dynamicsAPI.retrieveMultiple<T>(tableData);
```

**Screenshots**
![image](https://github.com/AleksandrRogov/DynamicsWebApi/assets/44670990/bd7bbd21-0479-43af-acb6-53bb2dbd3eb1)

**Your Setup (please complete the following information):**
 - Node v18.x.x
 - Dynamics 365 Online

**Comment by AleksandrRogov** [comment]
@rmeloni are you certain that the `serverUrl` is not `undefined` or `null`? This error will happen only if it is. Because if it is not defined it will try to get the client url from Dynamics Xrm object, but because it's also undefined it will throw that specific error.

**Comment by rmeloni** [comment]
> @rmeloni are you certain that the `serverUrl` is not `undefined` or `null`? This error will happen only if it is. Because if it is not defined it will try to get the client url from Dynamics Xrm object, but because it's also undefined it will throw that specific error.

It’s works! I forgot to change a environment variable.
