### ISSUE TITLE
`continueOnError` config parameter does not work as expected

### ISSUE THREAD

**Issue by albertjannap** [AleksandrRogov/DynamicsWebApi#178]
**DynamicsWebApi version**
v9.2

**Describe the bug**
I'm using the batch functionality to import records into a Dynamics org and I want to use the continueOnError config paramater. I set it to true but my request still fails. I also tried to use the headers paramater to pass the `Prefer` header with the value `odata.continue-on-error` but that also didn't work.

**Expected behavior**
I don't want the `executbeBatch` method to throw an error, the error should show in the results of the `executbeBatch` response. I tried to import 300 records with 3 records for which I expect an error so 297 records should be imported.

**Actual result**
![image](https://github.com/user-attachments/assets/d20ce692-87ba-41f3-8784-e39d69f905c0)
Throws an error and my application crashes.

**Code Snippet**
```js
dynamicsApiClient.startBatch();

for (const record of jsonData) {
    await dynamicsApiClient.create({
        data: record,
        collection: collectionName,
        returnRepresentation: true,
        select: headers,
    });
}

try {
    const res: any[] = await dynamicsApiClient.executeBatch({
        continueOnError: true,
        headers: {Prefer: 'odata.continue-on-error'},
    });
    console.log(res);
} catch (e) {
    console.log(e);
}
```

**Your Setup (please complete the following information):**
 - Node
 - Dynamics 365 Online

**Comment by AleksandrRogov** [comment]
hi @albertjannap thank you for submitting the issue. I will need to investigate this.

**Comment by albertjannap** [comment]
Some records were processed, for example
```javascript
  {
    '@odata.context': 'https://e-envaj-import-1721145565.crm4.dynamics.com/api/data/v9.2/$metadata#accounts(address1_name,address2_name,name,address1_line1,address1_city,address1_country,address1_stateorprovince,address1_postalcode,address1_telephone2,address1_telephone1,emailaddress1,websiteurl)/$entity',
    '@odata.etag': 'W/"6895922"',
    address1_name: 'Ashlyn',
    address2_name: 'Pinilla',
    name: 'Art Crafters',
    address1_line1: '703 Beville Rd',
    address1_city: 'Opa Locka',
    address1_country: 'Miami-Dade',
    address1_stateorprovince: 'FL',
    address1_postalcode: '33054',
    address1_telephone2: '305-670-9628',
    address1_telephone1: '305-857-5489',
    emailaddress1: 'apinilla@cox.net',
    websiteurl: 'http://www.artcrafters.com',
    accountid: 'ad6f0291-2248-ef11-bfe2-000d3a21c945',
    address1_composite: '703 Beville Rd\r\nOpa Locka, FL 33054\r\nMiami-Dade',
    oDataContext: 'https://e-envaj-import-1721145565.crm4.dynamics.com/api/data/v9.2/$metadata#accounts(address1_name,address2_name,name,address1_line1,address1_city,address1_country,address1_stateorprovince,address1_postalcode,address1_telephone2,address1_telephone1,emailaddress1,websiteurl)/$entity'
  }
```
I created the records for the account entity and for 3 records I set the postal code to 25 characters to test error handling for batch processing

**Comment by albertjannap** [comment]
@AleksandrRogov thx for your response:) the fix works and indeed the workaround is needed. Typical D365 behaviour...
I will close the issue

**Comment by albertjannap** [comment]
@AleksandrRogov If I add it I still got the error but when I remove the await the request got handled as I expected, errors are ignored:)

Ah yes using Promise.all is indeed a best practice
