### ISSUE TITLE
question - is there a way force to update when the lookup value doesn't exist

### ISSUE THREAD

**Issue by saostad** [AleksandrRogov/DynamicsWebApi#179]
When I am trying to update a record that includes a relation via a lookup field if the target value does not exist in the lookup table the update request fails with the error `A record with the specified key values does not exist in xxxxxx entity`. 
The C# SDK in this case, just ignores that property and updates the rest of the properties, is there a way to replicate the same behavior?

**Comment by AleksandrRogov** [comment]
I am quite positive that the SDK will also fail if you try to insert a record with a value in a lookup that references a non-existing record. It is also possible that I may be misunderstanding you. It would be better if you had an example of a request.
