### ISSUE TITLE
How to authentication with OAUTH?

### ISSUE THREAD

**Issue by roymap** [AleksandrRogov/DynamicsWebApi#2]
As per described here; https://msdn.microsoft.com/en-ca/library/gg327838.aspx

**Comment by AleksandrRogov** [comment]
Hi,
This functionality is not available yet. I'm currently working on it.
Thanks

**Comment by AleksandrRogov** [comment]
Hi Roy,
I've released a new version of DynamicsWebApi where I added a support of OAuth tokens. Please check an updated [readme](https://github.com/AleksandrRogov/DynamicsWebApi#dynamicswebapi-for-nodejs) for more information and examples.
I hope it will solve your problem.

Thank you
