### ISSUE TITLE
How to abort chained .then() functions

### ISSUE THREAD

**Issue by chuckokerstrom** [AleksandrRogov/DynamicsWebApi#21]
What technique would I use to abort a chain of .then() statements?

I can  use the javascript try/catch/throw, but was looking for something intrinsic to the Promise spec.  Are there other options available?

Chuck

**Comment by AleksandrRogov** [comment]
Hi @chuckokerstrom ,
There are many discussions on the internet about it, it would be better if you check this one: [https://stackoverflow.com/questions/29478751/how-to-cancel-an-emcascript6-vanilla-javascript-promise-chain](https://stackoverflow.com/questions/29478751/how-to-cancel-an-emcascript6-vanilla-javascript-promise-chain).

**Comment by chuckokerstrom** [comment]
Thanks for the response.  I ended up encapsulating your library's api 
calls with jquery's promise implementation and that seems to be working 
very well.  So in essence I'm using your .then() operations within the 
specific methods and jquery's to chain together sets of methods and 
provide the overall control and ability to bail out as needed.

Also wanted to pass on my appreciation for your api library - works 
great and really helps to organize & improve code readability.  Great work.


Chuck

**Comment by AleksandrRogov** [comment]
Hi @chuckokerstrom , 
I am glad you figured it out and thank you for your kind words they mean a lot to me.
