### ISSUE TITLE
Using FetchXML with associated link-entity alias returns unexpected response values

### ISSUE THREAD

**Issue by chuckokerstrom** [AleksandrRogov/DynamicsWebApi#23]
Using the following fetchxml statement the results for the linked attributes (those referred to with an alias of 'td') are returned as "td_x002e_gr_amount".  So instead of returning 'td.{attribute name} as expected this additional '_x002e_' string is embedded.  This string value appears to be consistent (so far) for any aliased attributes.  Is there a reason for this?  Is there a flag or option that I'm missing?

Regards,

Chuck

<fetch mapping="logical">
          <entity name="gr_aptransactionheader">
           <attribute name="gr_trasnactionnumber"/>
          <link-entity name="gr_aptransactionline" alias="td" to="gr_aptransactionheaderid" from="gr_transactionidid" >
                  <attribute name="gr_name" />
                   <attribute name="gr_amount" />
                         <filter type="and">
                            <condition attribute="cac_jobname" operator="eq" uitype="cac_job" value="{' + jobId + '}" />
                            <condition attribute="gr_postingstatus" operator="eq" value="0" />
                       </filter>
                        <link-entity name="cac_workcategory" from="cac_workcategoryid" to="cac_workcategory" alias="ad">
                            <filter type="and">
                            <condition attribute="cac_categorytype" operator="eq" value="' + categoryConstant + '" />
                            </filter>
                   </link-entity>
                  </link-entity>
             </entity>
         </fetch>

**Comment by chuckokerstrom** [comment]
Ok weird, the Xml code got removed.  Here it is now...

<fetch mapping="logical">
          <entity name="gr_aptransactionheader">
           <attribute name="gr_trasnactionnumber"/>
          <link-entity name="gr_aptransactionline" alias="td" to="gr_aptransactionheaderid" from="gr_transactionidid" >
                  <attribute name="gr_name" />
                   <attribute name="gr_amount" />
                         <filter type="and">
                            <condition attribute="cac_jobname" operator="eq" uitype="cac_job" value="{' + jobId + '}" />
                            <condition attribute="gr_postingstatus" operator="eq" value="0" />
                       </filter>
                        <link-entity name="cac_workcategory" from="cac_workcategoryid" to="cac_workcategory" alias="ad">
                            <filter type="and">
                            <condition attribute="cac_categorytype" operator="eq" value="' + categoryConstant + '" />
                            </filter>
                   </link-entity>
                  </link-entity>
             </entity>
         </fetch>

**Comment by chuckokerstrom** [comment]
[fetchxml_example.txt](https://github.com/AleksandrRogov/DynamicsWebApi/files/1797883/fetchxml_example.txt)

**Comment by AleksandrRogov** [comment]
Hi @chuckokerstrom ,
Yes, symbol `x002e` is an actual dot `.` but encoded, it is done to avoid JSON parsing errors. So, the actual response contains it.

At this moment DynamicsWebApi, does not decode such symbols, so you will need to use `td_x002e_gr_amount` to get the value. I did not notice that before, so I will implement a decoding in the next release and you will be able to use 'td.gr_amount`.

Thank you for submitting the issue!

**Comment by chuckokerstrom** [comment]
Just to close the loop on this.  I've installed the new release and it 
solves the issue.


Thanks,


Chuck
