### ISSUE TITLE
FetchXml Advanced Request

### ISSUE THREAD

**Issue by jmorton25** [AleksandrRogov/DynamicsWebApi#27]
Any plans to implement an "advanced" version of the FetchXml Requests? I'm passing a token explicitly to my calls using the Advanced Request object elsewhere, but I noticed that Fetch currently doesn't support that. 

I "hacked" my way into passing an additional parameter for my token into the basic FetchXml request, and one downstream thing I noticed is that when my FetchXml request is split into a "batch", the Authorization header is removed. I see you have supporting batch requests on the road map, so I imagine this fix will be relevant there as well. This was relatively easy to fix by adding an additional line after line 131 in sendRequest.js:

        for (var key in additionalHeaders) {
            batchBody.push(key + ': ' + additionalHeaders[key]);
            **if (key != 'Authorization') delete additionalHeaders[key];**
        }

Thanks again for all your work on the library!

**Comment by AleksandrRogov** [comment]
Thank you @jmorton25 , for submitting this issue. I will fix it in the next release.
And I appreciate your kind words.
