### ISSUE TITLE
Collection-valued navigation 

### ISSUE THREAD

**Issue by infiniteshroom** [AleksandrRogov/DynamicsWebApi#28]
Hi guys,

Just wondering if this library handles Collection-valued navigation? 

I've noticed if I try to use the expand property of the request object it just returns a @odata.nextLink. Naturally I'd want to avoid having to run a request to grab this data.

Is there anyway to handle that from the library?

Cheers,
Mark.

**Comment by AleksandrRogov** [comment]
Hi @infiniteshroom,
What do you mean by collection-valued navigation and what request are you trying to make?

Thanks

**Comment by infiniteshroom** [comment]
Hi,

Thanks for getting back to me. I'm trying to return a many to many relationship on an entity, but noticed that this returns a oDataNextLink just wondering how I would be able to get that information back, if that makes sense.

For instance getting all quotes associated with an opportunity.

Cheers.

**Comment by AleksandrRogov** [comment]
Thank you for the details. 
I am going to check what's going on with many to many relationships.

Meanwhile, what function are you using? Did you try to make a request using `retrieveAllRequest`? or you could try to compose a fetch xml and use `fetchAll`.

**Comment by infiniteshroom** [comment]
@AleksandrRogov No worries. Yeah it was a retrieveAllRequest. Will look into fetchAll as well.

I've worked around it just now by making a separate API request for the relation data. I think if there was a way to request the data for the oData NextLink for the many to many relationship that could work.

Thanks again for putting this library together it's been a massive help to me on interfacing dynamics and node, appreciate it.

Cheers,
Mark.

**Comment by AleksandrRogov** [comment]
Hi @infiniteshroom ,

I've looked at the Web API documentation and found out that it's designed this way by Microsoft. You will need to make another GET request using the value of the @odata.nextLink property to return the required data. [More info here](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-related-entities-by-expanding-navigation-properties), you will find it under `Retrieve related entities by expanding collection-valued navigation properties`.

Thanks
