### ISSUE TITLE
TypeScript: dynamics-web-api.d.ts is not a module

### ISSUE THREAD

**Issue by tdashworth** [AleksandrRogov/DynamicsWebApi#29]
The following code is producing the following error.

Code:
`import DynamicsWebApi from 'dynamics-web-api';`

Error:
`File 'c:/.../node_modules/dynamics-web-api/lib/dynamics-web-api.d.ts' is not a module.`

**Comment by tdashworth** [comment]
Thanks for your quick response. 

Is it something you are planning for the future? 

I would love to contribute but I am only just starting to learn TypeScript.

**Comment by AleksandrRogov** [comment]
I am planning to do it but it's not on my list of first things to do unfortunately.

Any contributions are welcome and if you would like to contribute I'll ask you to cover your code with tests. Not an easy task but if this is something you're interested in, let me know. :)

Best Regards,
Aleksandr

**Comment by rsquarev** [comment]
Please make this possible as soon as possible. It will be great help in our typescript based nodejs.

**Comment by AleksandrRogov** [comment]
Hi @rsquarev ,
I am working on adding d.ts files with TypeScript interfaces, I hope those will help.

**Comment by AleksandrRogov** [comment]
Hi @rsquarev ,
In case you are not getting notifications from DynamicsWebApi: I added TypeScript declaration files, you can download them from [here](../../tree/master/types/). Hope that will help.
