### ISSUE TITLE
executeFetchXml fails

### ISSUE THREAD

**Issue by wiese42** [AleksandrRogov/DynamicsWebApi#30]
pagenumber replacer produces bad results for a fetch statement like this:
<fetch mapping="logical" output-format="xml-platform" version="1.0" distinct="false">...</fetch>
works if I add "." and "-" to the pattern:
fetchXml = fetchXml.replace(/^(<fetch[\w\d\s'"=.-]+)/, replacementString);
note that this is not a suggested fix but a quick workaround for my special use case.

**Comment by AleksandrRogov** [comment]
Thank you for submitting the issue.
What's your special use case? How can I test it?
Thanks
