### ISSUE TITLE
auth fails for some adal versions

### ISSUE THREAD

**Issue by wiese42** [AleksandrRogov/DynamicsWebApi#31]
I am using adal.js from https://github.com/AzureAD/azure-activedirectory-library-for-js/tree/dev/dist for a client app (not a node app) that requires authorization. In this adal version the returned token is the token string itself. The token property accessToken is undefined.
Workaround: add (token.accessToken || token)  to the auth header instead.

**Comment by AleksandrRogov** [comment]
Thanks @wiese42 . I will add a condition there.
