### ISSUE TITLE
trouble with retreiveMultiple filter

### ISSUE THREAD

**Issue by wiese42** [AleksandrRogov/DynamicsWebApi#32]
I am trying to get all accounts where transactioncurrencyid has guid 784c6a92-....
I am using retreiveMultiple with filter statement
transactioncurrencyid eq 784c6a92-...
This gives me an exception:

  "message": "A binary operator with incompatible types was detected. Found operand types 'Microsoft.Dynamics.CRM.transactioncurrency' and 'Edm.Guid' for operator kind 'Equal'.",
  "type": "Microsoft.OData.Core.ODataException",

If instead I use the filter statement
_transactioncurrencyid_value eq 784c6a92-...
all is fine and I get my records. 

I think this should be done automatically by the library.

**Comment by AleksandrRogov** [comment]
Hi @wiese42 ,
Thanks for submitting this issue. 
I was thinking to automate that but there can be other types of lookups that can point to different types of entities, such as "Parent Customer", so the navigation property can be either "parentcustomerid_contact" or "parentcustomerid_account", how will the library "decide" which one you are planning to use?
Also, the name of the navigation property can be different from the schema name of the lookup, which means I will need to make an additional request to metadata before running a retrieve operation, which will slow down the performance of the library.
Anyway, I do have plans to utilize and parse CSDL metadata document in the future, and probably I will implement this enhancement, but for now I am closing this issue.

**Comment by wiese42** [comment]
maybe a filter builder would help. 
maybe some sanity checks, e.g.: if value has guid format then navigaton property should be of the form _name_suffix.

**Comment by AleksandrRogov** [comment]
As I explained earlier:
there can be other types of lookups that can point to different types of entities, such as "Parent Customer", so the navigation property can be either "parentcustomerid_contact" or "parentcustomerid_account", how will the library "decide" which one you are planning to use?

**Comment by wiese42** [comment]
Understood. That's why I was making suggestions how to make the situation for a library user less error prone/obscure. 
By the way: many thanks for your project. It saved me a lot of time.

**Comment by AleksandrRogov** [comment]
Hi @wiese42 . You are very welcome. I appreciate your support of the project!
