### ISSUE TITLE
 Getting error "Invalid URI: The hostname could not be parsed."

### ISSUE THREAD

**Issue by Bhavikaav** [AleksandrRogov/DynamicsWebApi#34]
Hi All, 

I am using the "dynamicsWebApi.update" method of the "dynamics-web-api" library to set a BPF stage of an entity as active in the CRM. But, I am getting below error:

"Invalid URI: The hostname could not be parsed.". 

Please help me to solve it. 

Thank you!!

**Comment by AleksandrRogov** [comment]
Hi @Bhavikaav ,
Can you please provide a piece of code where you initialize DynamicsWebApi object? And are you using NodeJs or a browser?

**Comment by Bhavikaav** [comment]
Hello AleksandrRogov,

Thanks for your prompt response.
Just for your knowledge, we are calling this function from a browser.
As you must be knowing, in MS Dynamics 365 V9, a separate entity is created by the system for each BPF (Business Process Flow).
My requirement is to create a function that updates the activestageid field in the entity created for the BPF.
I used your helper library to update the BPF entity but while executing the code, I found that the entity didn't get updated in CRM.
Thus, After I placed the request in Try{}Catch{} block as shown in the code below, I was able to catch the error saying "Invalid URI: The hostname could not be parsed." 
Please refer the function code as below:

function updateRelatedBPFEntityStage(executionContext, bpfEntitySchemaName, stageIdToUpdate) {
  if (stageIdToUpdate != null) {
    var formContext = getFormContext(executionContext);
    if (formContext != null) {
      var entityName = formContext.data.entity.getEntityName();
      var entityId = removeCurlyBraceFromGuid(formContext.data.entity.getId());
      var relatedBPFEntityRecordId = null;

      //Set the request parameters
      var requestToRetriveBPFEntityRecord = {
        collection: plural(bpfEntitySchemaName),
        select: ["businessprocessflowinstanceid"],
        filter: "_" + entityName + "id_value eq " + entityId,
        async: false
      };

      //Initialize a new instance of DynamicsWebApi with a configuration object
      var dynamicsWebApi = new DynamicsWebApi({ webApiVersion: '9.0' });

      //Perform a multiple records retrieve operation
      dynamicsWebApi.retrieveAllRequest(requestToRetriveBPFEntityRecord).then(function (response) {
        for (var i = 0; i < response.value.length; i++) {
          //alert(response.value);
          relatedBPFEntityRecordId = response.value[i].businessprocessflowinstanceid;
          alert("relatedBPFEntityRecord :" + relatedBPFEntityRecordId);
        }
      })
      .catch(function (error) {
        alert(error);
      });

      //debugger;

      //if (relatedBPFEntityRecordId != null) {
      var requestToUpdateBPFEntityStage = {
        key: relatedBPFEntityRecordId,
        collection: plural(bpfEntitySchemaName),
        entity: { 'activestageid@odata.bind': '/processstages(00000000-0000-0000-0000-000000000000)' },
        //Indicates whether the requests should be made synchronously or asynchronously. Default value is true (asynchronously).
        async: false,
      };

try{
      dynamicsWebApi.updateRequest(requestToUpdateBPFEntityStage).then(function (response) {
        alert("Record updated");
      })
        .catch(function (error) {
          alert(error.message); 
        });

    }
}catch(e){alert(e);}
  }
}

Waiting for your response.
Thank you,

**Comment by AleksandrRogov** [comment]
Can you please tell me what hostname it tries to make a request to? Is it correct or not? It seems like the URL host is missing something... most probably a schema.
Is this script on a CRM form or somewhere else? Is CRM on premise or online?

**Comment by AleksandrRogov** [comment]
Also, looking at your code, the promises you're calling are not chained which means you won't get a correct call sequence. Please check JavaScript Promise documentation to get more information.

**Comment by Bhavikaav** [comment]
Thank you for the response AleksandrRogov, I have resolved the error by removing a '/' from the below-highlighted code.
![bpfupdatecode](https://user-images.githubusercontent.com/27283027/45994100-c911d900-c0af-11e8-98d7-b35200849467.png)

**Comment by AleksandrRogov** [comment]
Great! Thanks for using DynamicsWebApi. I am closing this issue now.
