### ISSUE TITLE
includeAnnotations: "Microsoft.Dynamics.CRM.lookuplogicalname" ignored

### ISSUE THREAD

**Issue by wiese42** [AleksandrRogov/DynamicsWebApi#35]
I am calling dwa.rerieveRequest with property
includeAnnotations: "Microsoft.Dynamics.CRM.lookuplogicalname"
For some unknown reason this returns a result header with preference-applied: "odata.include-annotations="OData.Community.Display.V1.FormattedValue"" and indeed, the returned data includes formatted values but no logicalName info.  Is this expected behavior with dynamics 365 V9 Online? I realize that this is probably not an issue with your excellent library, but you might be able to give me some clues how to solve this nonetheless.

**Comment by wiese42** [comment]
seems to only work in combination with expand. closed.

**Comment by AleksandrRogov** [comment]
Thanks @wiese42 for submitting this issue. I am going to check it anyway.
