### ISSUE TITLE
Associate error

### ISSUE THREAD

**Issue by zabaat** [AleksandrRogov/DynamicsWebApi#37]
thank you for your quick help last time, hopefully this one isn't as bad of a user error.
Code
`dynamics
                        .associate(
                            'contacts',
                            record.contactid,
                            'parentcustomerid',
                            'accounts',
                            parentcustomerid
                        )
                        .then((data) => {
                            console.log('link worked', data)
                            context.res = {
                                body: record
                            }
                        })`

Error
`link failed { code: '0x8006088a',
 message: 'The URI segment \'$ref\' is invalid after the segment \'parentcustomerid\'.',
 innererror:
  { message: 'The URI segment \'$ref\' is invalid after the segment \'parentcustomerid\'.',
    type: 'Microsoft.OData.ODataException',
    stacktrace: '   at System.Web.OData.Routing.DefaultODataPathHandler.Parse(String serviceRoot, String odataPath, IServiceProvider requestContainer, Boolean template)\r\n   at System.Web.OData.Routing.DefaultODataPathHandler.Parse(String serviceRoot, String odataPath, IServiceProvider requestContainer)\r\n   at Microsoft.Crm.Extensibility.ODataV4.Routing.CrmODataPathHandler.Parse(String serviceRoot, String odataPath, IServiceProvider requestContainer)' },`

**Comment by AleksandrRogov** [comment]
Hi @zabaat ,
I will investigate this error. Thanks

**Comment by AleksandrRogov** [comment]
The third parameter must be a "Relationship Name" not an "Attribute Name".
So the request becomes like this:
```js
dynamicsWebApi.associate('contacts', record.contactid, 'account_primary_contact', 'accounts', parentcustomerid)
```

**Comment by zabaat** [comment]
Just a note that it's flipped
```
                    dynamics
                        .associate(
                            'accounts',
                            parentcustomerid,
                            'contact_customer_accounts',
                            'contacts',
                            record.contactid
                        )
```
