### ISSUE TITLE
Alternate keys does not allow to use integer value (it is forcing to use a string)

### ISSUE THREAD

**Issue by mfradcourt** [AleksandrRogov/DynamicsWebApi#38]
The current validation in the keyParameterCheck(...) function is forcing the key parameters to be of type string but it may happen that an integer is used.

For example, when a field is a drop down in Dynamics, the value behind is an integer. 
var key = "xxx='123456',yyy='137891',select_option=959600000"

The Dynamics CRM API is expecting to receive the value without single quote in case of an integer value.

I'm preparing a PR so no need to worry too much about this, just logging an issue so there is a trace about the feature/bug :-)

**Comment by AleksandrRogov** [comment]
Thanks @mfradcourt for submitting this issue and creating a pull request! I am closing this issue.
