### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by aliirz** [AleksandrRogov/DynamicsWebApi#4]
Hello

I am trying to run the basic example but i keep getting an unexpected error:

```bash
{ Error: Unexpected Error
    at IncomingMessage.<anonymous> (/Users/araza/NodeScripts/CRM-scripts/node_modules/dynamics-web-api/lib/requests/http.js:82:33)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) status: 401 }
```

Here is my code.. My client id and creds are correct because i tested by following the tutorial in this blog post:

http://alexanderdevelopment.net/post/2016/11/23/dynamics-365-and-node-js-integration-using-the-web-api/

Here is my code:
```javascript
var DynamicsWebApi = require('dynamics-web-api');
var AuthenticationContext = require('adal-node').AuthenticationContext;

//the following settings should be taken from Azure for your application
//and stored in app settings file or in global variables

//OAuth Token Endpoint
var authorityUrl = 'https://login.windows.net<guid>/oauth2/token';
//CRM Organization URL
var resource = 'https://myorg.crm.dynamics.com';
//Dynamics 365 Client Id when registered in Azure
var clientId = '<my-client-id-here>';

var username = '<my-username>';
var password = '<my-password>';

var adalContext = new AuthenticationContext(authorityUrl);

//add a callback as a parameter for your function
function acquireToken(dynamicsWebApiCallback) {
  //a callback for adal-node
  function adalCallback(error, token) {
    if (!error) {
      //call DynamicsWebApi callback only when a token has been retrieved
      dynamicsWebApiCallback(token);
    } else {
      console.log('Token has not been retrieved. Error: ' + error.stack);
    }
  }

  //call a necessary function in adal-node object to get a token
  console.log('calling auth')
  adalContext.acquireTokenWithUsernamePassword(resource, username, password, clientId, adalCallback);
}


//create DynamicsWebApi object
var dynamicsWebApi = new DynamicsWebApi({
  webApiUrl: 'https://myorg.api.crm.dynamics.com/api/data/v8.2/',
  onTokenRefresh: acquireToken
});

//call any function
dynamicsWebApi.executeUnboundFunction("WhoAmI").then(function(response) {
  console.log('Hello Dynamics 365! My id is: ' + response.UserId);
}).catch(function(error) {
  console.log(error);
});
```

Please help. This package really looks promising and would love to use it on my project.

**Comment by AleksandrRogov** [comment]
Hi aliirz,

As I can see from the error stack it is calling http package instead of https, and an example that you send calls organization by https, can you please check what your url is? And as I can understand you are getting this error when there is a call to `executeUnboundFunction`, is that correct?

**Comment by AleksandrRogov** [comment]
Hi aliirz,

I've released a patch for DynamicsWebApi v.1.2.3.

Can you please try it and see if it works for you now?

**Comment by swhillance-mphn** [comment]
I'm getting this error as well. Pretty much identical code. 

`
{ Error: Unexpected Error
    at IncomingMessage.<anonymous> (C:\Users\swhillance\Documents\GitHub\murray-butler-node\node_modules\dynamics-web-api\lib\requests\http.js:106:33)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  message: 'Unexpected Error',
  status: 401,
  statusText: undefined }
`

I have both http and https in my 'requires'

`
var express = require('express')
  , http = require('http')
  , https = require('https')
`

**Comment by AleksandrRogov** [comment]
@swhillance-mphn 401 means `UNAUTHORIZED` - are you sure you specified correct credentials?

**Comment by swhillance-mphn** [comment]
Ended up solving it by creating an 'Application User' in Dynamics 365, using the Application (Client) ID listed on the App Service in Azure. Once I did that I got status 200. Thanks Alek.

**Comment by AleksandrRogov** [comment]
@swhillance-mphn thanks for posting your solution.
