### ISSUE TITLE
Unexpected token ...

### ISSUE THREAD

**Issue by RoelVB** [AleksandrRogov/DynamicsWebApi#47]
I'm getting the error: `Unexpected token ...`

This is because of this line:
https://github.com/AleksandrRogov/DynamicsWebApi/blob/978500d052ba6ae124ea14fafb740e13fb1c9d3b/lib/requests/http.js#L64

This was introduced in this commit: https://github.com/AleksandrRogov/DynamicsWebApi/commit/bcf74c0c5f87c9839535f8e1d851f0514232541d

I always thought kind of extending of a dictionary is only available using TypeScript of any really modern JavaScript.

**Comment by AleksandrRogov** [comment]
Hi @RoelVB ,
Yes, I am going to refactor this. I want to support older versions of js.
Thanks

**Comment by AleksandrRogov** [comment]
@RoelVB may I ask you what version of Node.js you're using?

**Comment by RoelVB** [comment]
Thank you for your quick response.

I'm using 8.12 at the moment. I'm to afraid I'll break other projects if I upgrade.
But if an upgrade solves the problem I could give it a try.

**Comment by AleksandrRogov** [comment]
@RoelVB it will fix the problem. but I am going to push a patch soon, so you don't have to do that.

**Comment by ncjones** [comment]
@AleksandrRogov I just saw this. You should use eslint or similar to restrict language features or use babel to compile down to the supported runtime versions.

**Comment by AleksandrRogov** [comment]
hi @ncjones , you are right, I need to add compilation commands for this purpose.
