### ISSUE TITLE
Fetch picklist options

### ISSUE THREAD

**Issue by ncjones** [AleksandrRogov/DynamicsWebApi#50]
Is it possible to obtain the available picklist values for an attribute with this client library?

I'm currently using the following shell script to get the values I need but I'd like to automate this without using bash:

```bash
url="$(echo \
  "${base_url}" \
  "/EntityDefinitions(LogicalName=%27${entity}%27)" \
  "/Attributes(LogicalName=%27${attribute}%27)" \
  "/Microsoft.Dynamics.CRM.PicklistAttributeMetadata" \
  "?\$select=LogicalName" \
  "&\$expand=GlobalOptionSet(\$select=Options)" \
  | tr -d ' ')"

curl -f "${url}" \
  -H 'Accept: application/json' \
  -H 'OData-MaxVersion: 4.0' \
  -H 'OData-Version: 4.0' \
  -H 'Content-Type: application/json; charset=utf-8' \
  -H "Authorization: Bearer ${token}" \
  | jq '
    .GlobalOptionSet.Options[] |
    {
      value: .Value,
      label: .Label.LocalizedLabels[0].Label
    }'
```

The main issue with my bash script is that I have to manually generate and copy the auth token. Perhaps a more generic API should be exposed so that edge cases like this can be implemented by dropping down to the OData protocol like:

```javascript
const response = await dynamicsWebApi.odataGet(path);
``` 

or you could expose the token like:

```javascript
const token = await dynamicsWebApi.getToken();
```

**Comment by AleksandrRogov** [comment]
@ncjones , I guess you are looking for the following function:

```js
var entityKey = "LogicalName='contact'";
var attribute = "LogicalName='preferredcontactmethodcode'";
var attributeType = "Microsoft.Dynamics.CRM.PicklistAttributeMetadata";
var expandOptions = {
    property: "GlobalOptionSet", select: ["Options"]
};

const response = await dynamicsWebApi.retrieveAttribute(entityKey, attribute, attributeType, ["LogicalName"], [expandOptions]);
var options = response.GlobalOptionSet.Options;
```

**Comment by AleksandrRogov** [comment]
@ncjones or this:
```js
var request = {
    collection: "EntityDefinitions",
    key: "LogicalName='contact'",
    select: ["LogicalName"],
    navigationProperty: "Attributes",
    navigationPropertyKey: "LogicalName='preferredcontactmethodcode'",
    metadataAttributeType: 'Microsoft.Dynamics.CRM.PicklistAttributeMetadata',
    expand: [{
        property: "GlobalOptionSet", select: ["Options"]
    }]
};

const response = await dynamicsWebApi.retrieveRequest(request);
var options = response.GlobalOptionSet.Options;
```

**Comment by ncjones** [comment]
@AleksandrRogov That's perfect thanks! I guess this is obvious to anyone already familiar with the CRM OData API. Explicitly calling out this usecase in the docs would be helpful for noobs like me.

**Comment by AleksandrRogov** [comment]
@ncjones yeah, you need to know/realize that you need to fetch an Entity Metadata to get those pick list options prior to looking at my documentation. I could probably add a section called "Examples" somewhere, but I am afraid that it may to grow enormously because people have different knowledge levels.
