### ISSUE TITLE
dynamics-web-api.d.ts has optional parameter followed by mandatory

### ISSUE THREAD

**Issue by askhat** [AleksandrRogov/DynamicsWebApi#56]
Hi,

I'm just trying to pack into Docker container an app that relies on dynamics-web-api package. When I'm running build inside a container, I'm getting the following:

```
ERROR in /app/node_modules/dynamics-web-api/types/dynamics-web-api.d.ts
ERROR in /app/node_modules/dynamics-web-api/types/dynamics-web-api.d.ts(294,37):
TS1016: A required parameter cannot follow an optional parameter.
```

Indeed dynamics-web-api.d.ts at line 294 has this line:

```
executeBoundAction(id?: string, collection: string, actionName: string, requestObject?: Object, impersonateUserId?: string): Promise<any>;
                   ^^^
```

I'm guessing this is why the app isn't able to build. So, is it a mistake or am I missing something?

**Comment by AleksandrRogov** [comment]
hi @askhat, thanks for reporting this issue. I have made changes to d.ts files in v. 1.5.10.

**Comment by askhat** [comment]
Much obliged @AleksandrRogov
