### ISSUE TITLE
creating batch requests with upsert won't work

### ISSUE THREAD

**Issue by I2olanD** [AleksandrRogov/DynamicsWebApi#61]
Hello,

i'm trying to setup a batch request with upserts. The problem is, that the promise won't be resolved on the upsert call.

A single upsert call works. 

Example:
```javascript
async function upsertData(token, dataSet) {
	function aquireToken(dynamicsWebApiCallback) {
		dynamicsWebApiCallback(token);
	}
	const dynamicsWebApi = new DynamicsWebApi({
		webApiUrl: 'endpoint',
		onTokenRefresh: aquireToken
	});

	dynamicsWebApi.startBatch();

	try {
		await Promise.all(dataSet.map(async(data) => {
			const response = await dynamicsWebApi.upsert(`key='${data.key}'`, 'transactions', data);
			return response;
		}));
	} catch (error) {
		console.log(error);
	}

	dynamicsWebApi.executeBatch();
}
```

**Comment by AleksandrRogov** [comment]
hi @I2olanD , you don't have to resolve a promise when you call upserts between `startBatch` and `executeBatch`. Just resolve it in `executeBatch`:

```js
async function upsertData(token, dataSet) {
	function aquireToken(dynamicsWebApiCallback) {
		dynamicsWebApiCallback(token);
	}
	const dynamicsWebApi = new DynamicsWebApi({
		webApiUrl: 'endpoint',
		onTokenRefresh: aquireToken
	});

	dynamicsWebApi.startBatch();

	dataSet.map((data) => {
		dynamicsWebApi.upsert(`key='${data.key}'`, 'transactions', data);
	}));

	try {
		var response = await dynamicsWebApi.executeBatch();
	}
	catch (error){
		console.log(error);
	}
}
```

**Comment by I2olanD** [comment]
hey @AleksandrRogov . Thanks for the quick response! unfortunately the solution you provided does not help me either :(. I'm getting ```TypeError: Cannot read property '1' of null```since the batch array is empty....

It work's fine like this outside of a batch request.

**Comment by AleksandrRogov** [comment]
@I2olanD ok, I am going to check this.

**Comment by AleksandrRogov** [comment]
hi @I2olanD I have tested your scenario, I did not find issues with a batch request itself but there was an issue in parsing of a batch response that contains requests with alternate keys. I am not sure if this fixes your issue, please give it a try and let me know.

Other than that please check a map function that you have, maybe `dynamicsWebApi.upsert` is never called?

**Comment by I2olanD** [comment]
Hi @AleksandrRogov that was exactly the issue! I figuered out that the problem was not sending the batch, but handling the response, since it throws an error when the response gets parsed!

**Comment by AleksandrRogov** [comment]
@I2olanD great! I am closing this then.
