### ISSUE TITLE
Cannot Update Option Set Values (non-global)

### ISSUE THREAD

**Issue by trujaytim** [AleksandrRogov/DynamicsWebApi#63]
I am trying to update a field's option-set values and am having trouble finding the correct syntax. The option set is not "global" (i.e. the picklist options are defined local to the field). I have followed the below example for updating entity attributes:

```
var entityKey = "LogicalName='new_accountname'";
var attributeKey = "LogicalName='new_balance'";
var attributeType = 'Microsoft.Dynamics.CRM.MoneyAttributeMetadata';
dynamicsWebApi.retrieveAttribute(entityKey, attributeKey, attributeType).then(function(attributeMetadata){
    //1. change label
    attributeMetadata.DispalyName.LocalizedLabels[0].Label = 'New Balance';
    //2. update metadata
    return dynamicsWebApi.updateAttribute(entityKey, attributeMetadata, attributeType);
}).catch(function(error){
    //catch an error
});
```

Here is my attempt to apply the above to update some Option values - the attribute new_timstestoptions is already present on the contact entity:
```
var entityKey = "LogicalName='contact'";
var attributeKey = "LogicalName='new_timstestoptions'";
var attributeType = 'Microsoft.Dynamics.CRM.PicklistAttributeMetadata';
dynamicsWebApi.retrieveAttribute(entityKey, attributeKey, attributeType).then(function(attributeMetadata){
    attributeMetadata.Options = [{
            "Value": 100000000,
            "Color": "#0000ff",
            "IsManaged": false,
            "ExternalValue": "",
            "ParentValues": [],
            "MetadataId": null,
            "HasChanged": null,
            "Label": {
                "LocalizedLabels": [{
                        "Label": "A",
                        "LanguageCode": 1033,
                        "IsManaged": false,
                        "MetadataId": "0789c203-8a14-ea11-a811-000d3ad20d1d",
                        "HasChanged": null
                    }
                ],
                "UserLocalizedLabel": {
                    "Label": "A",
                    "LanguageCode": 1033,
                    "IsManaged": false,
                    "MetadataId": "0789c203-8a14-ea11-a811-000d3ad20d1d",
                    "HasChanged": null
                }
            },
            "Description": {
                "LocalizedLabels": [],
                "UserLocalizedLabel": null
            }
        }
    ];

    return dynamicsWebApi.updateAttribute(entityKey, attributeMetadata, attributeType);
}).catch(function(error){
    //catch an error
});

```
In the above sample, where the Options are being specified, the value holds all info from one of the current options.

The error is:

> An error occurred while validating input parameters: Microsoft.OData.ODataException: Does not support untyped value in non-open type

Any hints as to where I am going wrong?

**Comment by trujaytim** [comment]
Minor progress made - changing the above to set property OptionSet rather than Options allows the update to succeed (no error is reported by the Dynamics API), however the changes to the options do not get applied:
```
attributeMetadata.OptionSet = {
  "MetadataId": "0f89c203-8a14-ea11-a811-000d3ad20d1d",
  "Options": [{ ... options here ... }],
};
```
Any ideas? Thanks!

**Comment by AleksandrRogov** [comment]
hi @trujaytim , by looking at the documentation [here](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/query-metadata-web-api#querying-entitymetadata-attributes) it seems like you have to expand a OptionSet navigation property to get the value, I will try to get back to you asap with an example on how to update a local option set.
Thanks

**Comment by trujaytim** [comment]
Thanks Aleksandr, yes I perform that expand call when I "read" the local OptionSet values from the attribute. It is not clear to me if/how I can use expand during an update operation.

**Comment by AleksandrRogov** [comment]
@trujaytim  I have found a way to update an option set metadata. Though, I had to poke around a bit. Microsoft documentation did not help me with this as well. If you look [here](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/create-update-optionsets) they mention that you can update OptionSet by doing a `PUT` request by this url: 

> For a local option set use [Organization URI]/api/data/v9.0/EntityDefinitions(metadataid)/Attributes(metadataid)/Microsoft.Dynamics.CRM.PicklistAttributeMetadata/OptionSet.

Well... I tried, and it always returned me this error: **The requested resource does not support http method 'PUT'.**

Fortunately, there's a workaround, you can use an unbound action `UpdateOptionValue` to update local option set metadata (as well as a global one). So, here's a sample, based on your code:

```js
var entityKey = "LogicalName='contact'";
var attributeKey = "LogicalName='new_timstestoptions'";
var attributeType = 'Microsoft.Dynamics.CRM.PicklistAttributeMetadata';
var optionSetExpand = { property: "OptionSet", filter: "Name eq 'NAME OF YOUR OPTION SET'" };
dynamicsWebApi.retrieveAttribute(entityKey, attributeKey, attributeType, optionSetExpand )
    .then(function(attributeMetadata){
        var optionSet = attribute.OptionSet;
        //update an option label (for a sake of a sample)
        optionSet.Options[0].Label.LocalizedLabels[0].Label = "Update Option";
    
        return dynamicsWebApi.executeUnboundAction("UpdateOptionValue", {
            AttributeLogicalName: "new_timstestoptions",
            EntityLogicalName: "contact",
            Value: optionSet.Options[0].Value,
            Label: optionSet.Options[0].Label,
            MergeLabels: false
        });
    }).then(function(){
        //there's no response; otherwise it would throw an error
    }).catch(error){
        //catch error here
    });

```

I hope this answers your question. And I am going to report an issue with Microsoft Documentation.

Thanks

**Comment by trujaytim** [comment]
Ah, wow, thanks a lot Aleksandr, that does work just fine. I appreciate the time you spent investigating this for me.
