### ISSUE TITLE
Unable to perform Unbound Function RetrieveCurrentOrganization

### ISSUE THREAD

**Issue by ramarao9** [AleksandrRogov/DynamicsWebApi#65]
When trying to use the method executeUnboundFunction for the function 'RetrieveCurrentOrganization' the parameter conversion is not handled for enumerated values.

Please see the below link for an example of a valid url.
https://crmtipoftheday.com/757/passing-enumerated-values-to-web-api/

e.g. 
Expected
api/data/v9.1/RetrieveCurrentOrganization(AccessType=@p1)?@p1=Microsoft.Dynamics.CRM.EndpointAccessType'Default'

Actual

api/data/v9.1/RetrieveCurrentOrganization(AccessType=@p1)?@p1='Microsoft.Dynamics.CRM.EndpointAccessType'Default''  

Notice the additional quotes added above generated from the buildFunctionParameters.js is causing an error.

BTW  it's an awesome library!! Thank you!

**Comment by AleksandrRogov** [comment]
hi @ramarao9 ! Thank you for reporting this issue, it should now be fixed with 1.6.1.

And thank you for your kind words!

**Comment by ramarao9** [comment]
Thank you for fixing this so quickly!
