### ISSUE TITLE
GUID as alternate key value

### ISSUE THREAD

**Issue by m-szyszka** [AleksandrRogov/DynamicsWebApi#66]
I'm tryin to update single value  (or whole record) using Alternate Key.
When I'm using
```
keyName='xxx'
```
it's giving me message
```
Error: A record with the specified key values does not exist in 
```
which is OK,
but when key value is a UUID and exists in CDS, library says
```
<entity_name> With Id = 44771e9d-b5ea-4b86-92d3-72be52d6b807 Does Not Exist
```
Looks like UUID in Alternate Key value is recognized and processed as Primary Key.
Result: can;t update entity using Alternate Key with UUID value.

**Comment by AleksandrRogov** [comment]
hi @m-szyszka. 
I will try to reproduce it. It would be great if you had a code example of what you are doing, so I could provide you with a workaround for your case, but you can simply use the UUID value without providing the key name for the primary key.

```js
let toUpdate = { name: "update this lead" };
let id = "44771e9d-b5ea-4b86-92d3-72be52d6b807";
//update with a primary key:
let result = await dynamicsWebApi.update(primaryKey, "leads", toUpdate);
```

**Comment by AleksandrRogov** [comment]
I think I misunderstood your issue. You don't want that UUID to be recognized as a primary key.
Ok, I'll take a look at that.

**Comment by m-szyszka** [comment]
I want to use UUID as Alternate Key value, and it's not working for me. When Alternate Key value is a normal string, it's working.
Part of my code:
```
const keyValuePair = { my_status: status };
    const key = `my_reference='${myReference}'`;
    logger.info(`Trying to update  entity ${myReference} status to ${status}`);
    return dynamicsWebApi.updateSingleProperty(key, ENTITY_COLLECTION_NAME,
      keyValuePair, ['return=representation'])
```
When "myReference" is an UUID, it's not working.

**Comment by AleksandrRogov** [comment]
@m-szyszka please download a new patch 1.6.3 and let me know if it fixes your issue!
Thank you for submitting the issue!

**Comment by m-szyszka** [comment]
It's working now, thanks for fast response
