### ISSUE TITLE
Multi-level expands

### ISSUE THREAD

**Issue by io-timeout** [AleksandrRogov/DynamicsWebApi#67]
Firstly, thank you for the great work you have done on this library!

According to the documentation, multi-level expands are not yet implemented.  This is true in so far that the Expand type definition does not provide an official way to define them.

I looked into the RequestConverter.convertRequestOptions code and it looked like they may naturally be supported as this code recursively calls RequestConverter.convertRequestOptions when processing the expand options.

I subsequently tested a retrieveMultipleRequest with multi-level expands as follows:
```
  const result = await dynamicsClient.retrieveMultipleRequest({
    collection: 'topLevelCollection',
    expand: [
      {
        property: 'firstLevelToExpand,
        select: ['field1', 'field2'],
        expand: [
          {
            property: 'secondLevelToExpand',
            select: ['field1', 'field2']
          }
        ]
      }
    ]
  })
```

This worked perfectly!   

- Is there a reason that they are not officially supported?
- Is it possible to add a nested expand into the type definition in order to support these officially?

**Comment by sgardnerdell** [comment]
That was quick!  Thank you 👍
