### ISSUE TITLE
Getting issue when using DynamicsWebApi in SPFx

### ISSUE THREAD

**Issue by gauravgoyal5** [AleksandrRogov/DynamicsWebApi#68]
Hi ,
I am using DynamicsWebApi in SPFx solution & following the instruction given in the urls :

- https://www.npmjs.com/package/dynamics-web-api?ref=hackernoon.com

- https://hackernoon.com/integrating-with-the-dynamics-rest-api-using-nodejs-3wk323t

But when I am bundling , getting the issue :
![image](https://user-images.githubusercontent.com/6926513/85944649-1e021380-b956-11ea-8dd7-809fb9855fb7.png)

Attached code file :
[spfx-dynamics.zip](https://github.com/AleksandrRogov/DynamicsWebApi/files/4842062/spfx-dynamics.zip)

**Comment by AleksandrRogov** [comment]
@gauravgoyal5 as I can see from the stack trace the error is coming from another module, not DynamicsWebApi. 

This one: `Can't resolve 'fs' in '....\temp\node_modules\request\lib'`.
Here are some links related to this issue:

* https://github.com/react-boilerplate/react-boilerplate/issues/2279
* https://stackoverflow.com/questions/46775168/cant-resolve-fs-using-webpack-and-react

**Comment by AleksandrRogov** [comment]
Also, I am not very familiar with React.js and may be wrong, but it seems like you should use code compiled for the browser and not Node.js package itself. The code for the browser is located [here](../../DynamicsWebApi/tree/master/dist).

**Comment by gauravgoyal5** [comment]
Thanks for the reply. I will try & use the JS code.

**Comment by AleksandrRogov** [comment]
Let me know if you still experience this issue. I am gonna close it for now.
