### ISSUE TITLE
response headers in error

### ISSUE THREAD

**Issue by m-szyszka** [AleksandrRogov/DynamicsWebApi#69]
Hi!
I want to implement retry strategy for dynamics calls and noticed that there are no dynamics headers in error response. To be more specific, I want to retry call in case of HTTP Status 429 (Too Many Requests). I can see "status" field in "error" object, but for 429 Dynamics returns also standard Retry-After header, which is missing.
Is it possible to add it in current 1.X version?

**Comment by AleksandrRogov** [comment]
hi @m-szyszka , sure, I will find a way to add headers to error object.

**Comment by AleksandrRogov** [comment]
@m-szyszka , I've released a new patch `1.6.7` with a requested change. You can access headers through `error.headers` property. Please let me know if it solves the problem you have.
Thanks

**Comment by m-szyszka** [comment]
I checked and it looks fine, thanks for the quick response!
