### ISSUE TITLE
Use Content-ID inside a request payload for association in batching causes web api error

### ISSUE THREAD

**Issue by CrestHawk** [AleksandrRogov/DynamicsWebApi#70]
Hey,

I was trying to use the batch operation to associate a custom entity to the quote entity using the content id and navigation property required. However this causes an error with the following message from the Dynamics web api.

status code - 500
message - 'Resource not found for the segment \'$1\''

At first I thought it might have been something to do with the relationship between the quote and my custom entity. However I get the same error using the code in your simple example in the docs for contact and order (pasted below)

I am using an om prem instance for version 9 so I am unsure whether the same issue occurs with a cloud instance.

```
var contact = {
    firstname: 'John',
    lastname: 'Doe'
};
 
var order = {
    name: '1 year membership',
    //reference a request in a navigation property
    'customerid_contact@odata.bind': '$1'
};
 
dynamicsWebApi.startBatch();
dynamicsWebApi.createRequest({ entity: contact, collection: 'contacts', contentId: '1' });
dynamicsWebApi.createRequest({ entity: order, collection: 'salesorders' });
 
dynamicsWebApi.executeBatch()
    .then(function (responses) {
        //in this case both ids exist in a response
        //which makes it a preferred method
        var contactId = responses[0];
        var salesorderId = responses[1];
    }).catch(function (error) {
        //catch error here
    });
```

Many thanks

**Comment by AleksandrRogov** [comment]
hi @CrestHawk, tried to use this example and everything worked well for me.
What version of DynamicsWebApi are you using? And can you please send me the batch payload from the request that your app makes (**don't forget to strip all sensitive data from it**).

**Comment by AleksandrRogov** [comment]
It should look something like this:

```
--dwa_batch_07d44587-0f46-4c2d-a2c2-3ac33755def8
Content-Type: multipart/mixed;boundary=changeset_c96f113f-54a4-4ef6-972b-5b44c5271cf7

--changeset_c96f113f-54a4-4ef6-972b-5b44c5271cf7
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 1

POST https://orgurl/api/data/v9.1/contacts HTTP/1.1
Content-Type: application/json

{"firstname":"John","lastname":"Doe"}

--changeset_c96f113f-54a4-4ef6-972b-5b44c5271cf7
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 100001

POST https://orgurl/api/data/v9.1/salesorders HTTP/1.1
Content-Type: application/json

{"name":"1 year membership","customerid_contact@odata.bind":"$1"}

--changeset_c96f113f-54a4-4ef6-972b-5b44c5271cf7--

--dwa_batch_07d44587-0f46-4c2d-a2c2-3ac33755def8--
```

**Comment by CrestHawk** [comment]
Hey @AleksandrRogov,

Sure thing, here is some more information on my setup:

dynamics-web-api package version: 1.6.8
On prem organisation version: 9.0.16.7
Web api version: v9.0

I noticed above your batch request is using version 9.1 of the api, could this be the reason I am getting differing result from yourself?

Is there some configuration I can set for the dynamics-web-api package so that it will log out that batch payload for me?

Many thanks.

**Comment by AleksandrRogov** [comment]
@CrestHawk so, your payload is the same as in my example?

**Comment by AleksandrRogov** [comment]
I made a request to 9.0, it worked well as well.

```
--dwa_batch_cf728e61-f2a3-4967-b26d-cac9cb5fbbe4
Content-Type: multipart/mixed;boundary=changeset_d1488771-2852-4858-b561-3f6e07ee772b

--changeset_d1488771-2852-4858-b561-3f6e07ee772b
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 1

POST https://orgurl/api/data/v9.0/contacts HTTP/1.1
Content-Type: application/json

{"firstname":"John","lastname":"Doe"}

--changeset_d1488771-2852-4858-b561-3f6e07ee772b
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 100001

POST https://orgurl/api/data/v9.0/salesorders HTTP/1.1
Content-Type: application/json

{"name":"1 year membership","customerid_contact@odata.bind":"$1"}

--changeset_d1488771-2852-4858-b561-3f6e07ee772b--

--dwa_batch_cf728e61-f2a3-4967-b26d-cac9cb5fbbe4--
```

![image](https://user-images.githubusercontent.com/1893650/88290142-4adee780-ccc4-11ea-9bfb-586a113b9000.png)

**Comment by CrestHawk** [comment]
Hey @AleksandrRogov 

Yes I am using the same code as your example.

I don't know how much of a difference it makes but I am using this in a large Typescript application that already has a substantial amount of node_modules also being pulled in as dependencies.

I could give it another try in a small isolated application using raw Javascript to see if that makes a difference and get back to you later this afternoon if that helps?

Are you using an application such as fiddler to get access to the raw batch payload that the package is generating and sending? So far I haven't managed to obtain the raw payload that's  being generated and sent to my Dynamics instance.

 Are you also testing this against a cloud or on premises instance?

Many thanks.

**Comment by AleksandrRogov** [comment]
@CrestHawk i do test it against cloud. i don't have an access to on-prem. Theoretically, they should have identical web api back-end. Unless, there's a bug in the version you have, because that error comes from the system.

Yes, you could use either fiddler or just put a breakpoint in `node_modules\dynamics-web-api\lib\requests\http.js` line 23 and copy the value of the `data` variable.

**Comment by AleksandrRogov** [comment]
also after reading about this exception, it seems like it happens when the resource name was incorrectly specified, for example: `https://orgurl/api/data/v9.0/salesorder` <- notice that there's "s" missing in the end. That's when you normally would see that error.

**Comment by CrestHawk** [comment]
Hey @AleksandrRogov 

Thanks for pointing out where to put the break point, I've just retrieved the payload and this is what is being generated for me (I've removed my org url)

```
--dwa_batch_fc539a96-57db-42a4-aa88-05c69cff9174
Content-Type: multipart/mixed;boundary=changeset_4f39cb0e-3617-4c5b-9218-19789ac5c92c

--changeset_4f39cb0e-3617-4c5b-9218-19789ac5c92c
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 1

POST https://tor-engdyn-crm2.tstengdyn.net/crmtomdev9/api/data/v9.0/contacts HTTP/1.1
Content-Type: application/json

{"firstname":"John","lastname":"Doe"}

--changeset_4f39cb0e-3617-4c5b-9218-19789ac5c92c
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 100001

POST https://tor-engdyn-crm2.tstengdyn.net/crmtomdev9/api/data/v9.0/salesorders HTTP/1.1
Content-Type: application/json

{"name":"1 year membership","customerid_contact@odata.bind":"$1"}

--changeset_4f39cb0e-3617-4c5b-9218-19789ac5c92c--

--dwa_batch_fc539a96-57db-42a4-aa88-05c69cff9174--
```

This payload gave me the same 500 error. I've included the stack trace below.

Does this same payload work for you? If so it may be as you say a bug with my particular version.

message:'Resource not found for the segment '$1'.'
stacktrace:'   at Microsoft.OData.UriParser.ODataPathParser.CreateDynamicPathSegment(ODataPathSegment previous, String identifier, String parenthesisExpression)\r\n   at Microsoft.OData.UriParser.ODataPathParser.CreateFirstSegment(String segmentText)\r\n   at Microsoft.OData.UriParser.ODataPathParser.ParsePath(ICollection`1 segments)\r\n   at Microsoft.OData.UriParser.ODataPathFactory.BindPath(ICollection`1 segments, ODataUriParserConfiguration configuration)\r\n   at Microsoft.OData.UriParser.ODataUriParser.Initi…ompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()'

Many thanks

**Comment by AleksandrRogov** [comment]
@CrestHawk yes, my payload is exactly the same as yours and it works.

It seems like there's something wrong internally in your system, probably a bug. I've noticed that your patch is not the latest one, maybe installing new patches will fix this issue? You could also try contacting Microsoft about it, maybe they will help. Just send them the batch payload and the error description, exactly as you did in your last message.

Just to be sure, I would suggest to check the name of the navigation property `customerid_contact` maybe it's different for on-premise (which it should not).. you can do this by downloading CSDL document from `https://yourorg/api/data/v9.0/$metadata`.

```xml
<NavigationProperty Name="customerid_contact" Type="mscrm.contact" Nullable="false" Partner="order_customer_contacts">
    <ReferentialConstraint Property="_customerid_value" ReferencedProperty="contactid" />
</NavigationProperty>
```

Sorry that I can't help you further.

P.S. Please let me know if you fix this issue and what fixed it.
