### ISSUE TITLE
Trying to set timeout using setConfig() function returns an error.

### ISSUE THREAD

**Issue by goldesjuan** [AleksandrRogov/DynamicsWebApi#73]
I have the requirement of having different timeouts for different types of operations, currently I am trying to set a specific timeout for batch operations and every time I call `setConfig({ timeout: 8000 })` I get the same error: "Xrm Context is not available", no matter where I call it from.

Also, it would be super helpful if the timeout could be specified on a per-operation basis as part of the request parameters passed to the functions.

**Comment by AleksandrRogov** [comment]
@goldesjuan are you calling it from Dynamics 365 web resource or from node.js app?

And, sure, I will add timeout to request object.

**Comment by AleksandrRogov** [comment]
Hi @goldesjuan,

You can now set `timeout` in the request. Please download `v.1.6.10`.
Thanks!
