### ISSUE TITLE
executeBatch throws an array of objects in case of an error

### ISSUE THREAD

**Issue by marcinmo-kainos** [AleksandrRogov/DynamicsWebApi#77]
Hello Aleksander,

is it documented somewhere what it means that the executeBatch can throw an array of objects instead of an Error?

I could not find anything in the documentation about it myself :(

Cheers,
Marcin

**Comment by AleksandrRogov** [comment]
hi @marcinmo-kainos ,
Do you mean this one? https://github.com/AleksandrRogov/DynamicsWebApi/releases/tag/v1.6.0

Let me know if this example helps. I may actually need to add it to readme.

**Comment by marcinmo-kainos** [comment]
Thank you

Now it's very clear :)

Cheers
