### ISSUE TITLE
fetchAll returns no more than 5000 items

### ISSUE THREAD

**Issue by Lebowskovitch** [AleksandrRogov/DynamicsWebApi#79]
Hi everyone,

I'm facing a weird issue. The same fetchXml query returns more than 5000 items (5482 exactly) in one of our app in production (so it's ok) but when I do the same in a local console app, same version of the lib, same xml (copy paste), same configuration (apparently), it returns 5000, as if the paging info was not returned correctly.

I tried to add a log line to see if the response.PagingInfo was there but it's undefined in the console app.

I don't know where to search anymore. Anyone has an idea on this ?
Thanks !

**Comment by AleksandrRogov** [comment]
@Lebowskovitch can I ask you to try to send the same request manually and see if the paging cookie is in the response? You can catch the request details using Fiddler.
I need more information to figure out where the issue is.

**Comment by Lebowskovitch** [comment]
@AleksandrRogov Ok so I tried to do the request manually with postman and I got the paging cookie, and 5000 items in the value, as expected.

```
"@Microsoft.Dynamics.CRM.fetchxmlpagingcookie": "<cookie pagenumber=\"2\" pagingcookie=\"%253ccookie%2520page%253d%25221%2522%253e%253cfullname%2520last%253d%2522Taryn%2520Kassulke%2522%2520first%253d%2522Aaliyah%2520Mann%2522%2520%252f%253e%253ccontactid%2520last%253d%2522%257b351E7841-0C19-EB11-A812-000D3AB36281%257d%2522%2520first%253d%2522%257bB8107841-0C19-EB11-A812-000D3AB36281%257d%2522%2520%252f%253e%253c%252fcookie%253e\" istracking=\"False\" />",
    "value": [
// ...
```

It's like the lib would behave differently in a terminal app.
FYI when we call the `fetchAll` method, we never use any additional params other than: the target entity, and the XML. (e.g. includeAnnotations or something). But until now, it always worked, and still works in production in our express app.

**Comment by AleksandrRogov** [comment]
@Lebowskovitch hi. I've ran tests and the `PagingInfo` object exists in the fetch response with the cookie you provided. Are you sure that the `PagingInfo` is null?

![image](https://user-images.githubusercontent.com/1893650/97783618-6d0fbd80-1b6f-11eb-84cf-b3b16fa96e9e.png)

**Comment by Lebowskovitch** [comment]
@AleksandrRogov Hi ! Here is an example of what I see on my side. I'm doing a `fetchAll()` request.
![capture](https://user-images.githubusercontent.com/3788053/97854131-54331380-1cf9-11eb-8287-a589ab6f1158.png)

As you can see, it seems the paging cookie is present in the response, but the `PagingInfo` is still `undefined`.

**Comment by Lebowskovitch** [comment]
I think I found something interesting:
![1st](https://user-images.githubusercontent.com/3788053/97855702-6f068780-1cfb-11eb-9166-b9ed9d490ff7.png)
![2nd](https://user-images.githubusercontent.com/3788053/97855709-7168e180-1cfb-11eb-95f0-a57aa6ed14a9.png)

After response is parsed, `PagingInfo` seems ok, but apparently, it is not included in the final `response` object which is passed to the promise resolve callback.

**Comment by Lebowskovitch** [comment]
Well, . I can't explain what happened. It seems now that the request returns more than 5000 items as expected.
Since the last screenshot above, I didn't change anything in the code, anywhere, I'm just doing some step-by-step debug since this morning. Now the `PagingInfo` is filled.
I'm sorry, I think we can close this issue and we'll never know what happened.

**Comment by AleksandrRogov** [comment]
@Lebowskovitch great! i will test the request with `useEntityNames` parameter. Maybe there's an issue with it somewhere.

**Comment by Lebowskovitch** [comment]
I tried to investigate further but had to stop at some point. I think it has to do with the responseParams variable, which seems to lose the pageNumber property somewhere before the fetch request.

**Comment by AleksandrRogov** [comment]
ok thanks. I will check that.
