### ISSUE TITLE
Synchronous request

### ISSUE THREAD

**Issue by sebastiensapet** [AleksandrRogov/DynamicsWebApi#8]
Hello,

How can I use your library if I want to make synchronous request ? Because I think all requests are asynchrounous.

Thanks,
Sebastien

**Comment by AleksandrRogov** [comment]
Hi @sebastiensapet ,
It's fully asynchronous, no synchronous requests are supported in a current version.

Thanks

**Comment by sebastiensapet** [comment]
Ok, thanks for your reply.

Regards,
Sebastien
Le 20 juil. 2017, à 00:03, Aleksandr Rogov <notifications@github.com<mailto:notifications@github.com>> a écrit:

Hi @sebastiensapet<https://github.com/sebastiensapet> ,
It's fully asynchronous, no synchronous requests are supported in a current version.

Thanks
