### ISSUE TITLE
Uploading files to attachment fields

### ISSUE THREAD

**Issue by ThePridestalker** [AleksandrRogov/DynamicsWebApi#82]
Is there an easy way to do it through the api?

**Comment by AleksandrRogov** [comment]
@ThePridestalker yes, just create an `annotation` entity with `documentBody` where you encode your document/file. it's going to be pretty much the same as here: https://www.cloudfronts.com/create-notes-attachment-using-webapi/

**Comment by ThePridestalker** [comment]
Can you exemplify with your library? I'm new to the whole microsoft environment and I'm using your library to get some abstraction.

My company uses powerapps, and I need to attach a file (in my case .json file) to an entity, and retrieve its data. I'm using your library for uploading and retrieving the odata json, but I dont see how can I upload files. 

The cloundfronts link encodes an img as base64, but its different stuff than mine, might be because of powerapps.

My entity is called crbc6_testsavingfile. A test record looks like this (crbc6_filefield being the attachment field, that shows an ID of the file uploaded, but I don't know how to query to get its content):

```
{
  "@odata.context": "https://instancename.api.crm4.dynamics.com/api/data/v9.1/$metadata#crbc6_testsavingfile/$entity",
  "@odata.etag": "W/\"1726765\"",
  "_owningbusinessunit_value": "79678c2f-5e10-eb11-a812-000d3abaa203",
  "crbc6_name": "test",
  "statecode": 0,
  "statuscode": 1,
  "_createdby_value": "2cc07adb-4414-eb11-a812-000d3ab9bf1d",
  "crbc6_testsavingfileid": "d5ab730e-8d2d-eb11-a813-0022489b5d6b",
  "crbc6_filefield_name": "MyFile.json",                             //--> filename shows here
  "_ownerid_value": "2cc07adb-4414-eb11-a812-000d3ab9bf1d",
  "modifiedon": "2020-11-25T14:48:44.000Z",
  "_owninguser_value": "2cc07adb-4414-eb11-a812-000d3ab9bf1d",
  "_modifiedby_value": "2cc07adb-4414-eb11-a812-000d3ab9bf1d",
  "versionnumber": 1726765,
  "crbc6_filefield": "f4d4e879-8d2d-eb11-a813-0022489b5d6b",         //--> I get the file id that i dont know how to use to request
  "createdon": "2020-11-23T13:09:03.000Z",
  "importsequencenumber": null,
  "overriddencreatedon": null,
  "_owningteam_value": null,
  "_modifiedonbehalfby_value": null,
  "timezoneruleversionnumber": null,
  "utcconversiontimezonecode": null,
  "_createdonbehalfby_value": null,
  "oDataContext": "https://instancename.api.crm4.dynamics.com/api/data/v9.1/$metadata#crbc6_testsavingfile/$entity"
}
```

I created a form from the powerapps interface to be able to have a file in the record to test the request, but I'm forced to create the record before uploading a file, at least through the powerapps form interface, and I don't know if i can do it all in one request using your library.

**Comment by AleksandrRogov** [comment]
```js
const fileBytesEncodedWithBase64 = btoa(fileBytes);

const annotation = {
    'objectid_crbc6_testsavingfile@odata.bind': 'crbc6_testsavingfiles(23e6ee7c-5812-e911-a96b-000d3a3638df)',
    subject: "test file",
    filename: "testfile.json",
    documentBody: fileBytesEncodedWithBase64 
};

const annotationId = await dynamicsWebApi.createRequest({
    collection: "annotations",
    entity: annotation
});
```

**Comment by AleksandrRogov** [comment]
If you want to do it all in a single request, you will need to use batch request.

```js



const yourEntityRecord = { ... };

const fileBytesEncodedWithBase64 = btoa(fileBytes);

const annotation = {
    'objectid_crbc6_testsavingfile@odata.bind': '$1',
    subject: "test file",
    filename: "testfile.json",
    documentBody: fileBytesEncodedWithBase64 
};

dynamicsWebApi.startBatch();
dynamicsWebApi.createRequest({
    collection: "crbc6_testsavingfiles",
    entity: yourEntityRecord,
    contentId: '1'
});
dynamicsWebApi.createRequest({
    collection: "annotations",
    entity: annotation
});

const results = await dynamicsWebApi.executeBatch();
```

**Comment by AleksandrRogov** [comment]
I've just noticed that you are using a file field. Unfortunately, I have never worked with the new File and Image fields, so I cannot give you an answer how it works at this moment. I will need some time to test it in my environment.

**Comment by AleksandrRogov** [comment]
Currently, it's not possible to upload or download files from File Fields using `DynamicsWebApi`. I am working on adding this functionality in the next `1.7.0` release. Thank you.

**Comment by ThePridestalker** [comment]
Thanks you too for the awesome work. Do you have an ETA on `1.7.0` ?

**Comment by AleksandrRogov** [comment]
@ThePridestalker before the end of this week 100%, most probably on Saturday. I hope it's ok for you.

**Comment by ThePridestalker** [comment]
@AleksandrRogov Saturday is okay for me 👍

**Comment by ThePridestalker** [comment]
I don't know if there will be any difference with the file type, but in my case, I need to upload a json. A coworker sent me an example using patch request to ODATA, and he basicly sends the json in the body with a 'x-ms-file-name' header indicating the name of the file.

**Comment by AleksandrRogov** [comment]
@ThePridestalker yes, that's what I am implementing in the library

**Comment by AleksandrRogov** [comment]
@ThePridestalker the new version `1.7.0` is released and has file upload/download and delete functionalities. Please refer to readme to know more.
Thank you and hope this helps!

**Comment by ThePridestalker** [comment]
Sorry for asking again, but I find this problem when I try to upload a json. 

**"Content range is either not valid or size of the payload [37] doesn't match with the chunk size provided."**

I tried making it a buffer with Buffer.from(data) but it doesnt even work, so I did JSON.stringify(data) and when I send it as a string I get that error, else response is undefined after calling dynamicsWebApi.uploadFile with the parameters

**Comment by AleksandrRogov** [comment]
@ThePridestalker it must be a Buffer, not string.

```js
const json = JSON.stringify(data);
const fileBuffer = Buffer.from(json , "utf-8");

await dynamicsWebApi.uploadFile({
        collection: 'dwa_filestorages',
        key: '00000000-0000-0000-0000-000000000001',
        fieldName: 'dwa_file',
        fileName: filename
        data: fileBuffer ,
    })
```

**Comment by AleksandrRogov** [comment]
@ThePridestalker the response will be undefined. that's normal.

**Comment by ThePridestalker** [comment]
Oh that's what I didn't know, works perfect now thanks! 👍
