### ISSUE TITLE
V2 Timeline & support for MSAL.js

### ISSUE THREAD

**Issue by jync** [AleksandrRogov/DynamicsWebApi#83]
Just planning ahead. I can see v2 is coming and I can see MS is deprecating ADAL.js. What is DynamicsWebApi's timeline on these items? Is there a way we could preview v2?

**Comment by AleksandrRogov** [comment]
hi @jync, DynamicsWebApi does not depend on ADAL, it just needs a token. It can even be a custom authentication functionality. So, I am not worried about that.

You can preview v2 in `typescript` branch, it should be visible to everyone. Some parameters and return objects will most likely change but not too much. So, it should give you an idea what to expect from v2.

**Comment by pixelpaulaus** [comment]
anyone have some examples of using the new msal-node? i cant get it to work

**Comment by AleksandrRogov** [comment]
@pixelpaulaus sorry forgot to ping, my reply is above.

**Comment by pixelpaulaus** [comment]
that help a great deal, thanks

**Comment by AleksandrRogov** [comment]
glad it helped!
