### ISSUE TITLE
DynamicsWebApi with Promises

### ISSUE THREAD

**Issue by pixelpaulaus** [AleksandrRogov/DynamicsWebApi#86]
Your link to the "ES6 Promises: DynamicsWebApi with Promises."  is a 404 error

**Comment by AleksandrRogov** [comment]
@pixelpaulaus here's the link: https://github.com/AleksandrRogov/DynamicsWebApi/blob/master/dist/dynamics-web-api.js

**Comment by pixelpaulaus** [comment]
sorry how would i "require" that at top of my JS file

**Comment by AleksandrRogov** [comment]
are you using node.js or developing js for a form web resource?

**Comment by AleksandrRogov** [comment]
Closing this issue, due to inactivity.
