### ISSUE TITLE
Can not get StatusAttributeMetadata/Can not expand navigation property to StatusOptionMetadata

### ISSUE THREAD

**Issue by MrMoehner** [AleksandrRogov/DynamicsWebApi#87]
Hello, 

i am trying for more than one day now to process the following request with DynamicsWebApi. This requests works in the browser, if you are logged in (and maybe if you are admin). 

https://XXXXXYOURURLXXXX.dynamics.com/api/data/v9.1/EntityDefinitions(LogicalName='opportunity')/Attributes/Microsoft.Dynamics.CRM.StatusAttributeMetadata?$select=LogicalName&$expand=OptionSet($select=Options)
    

But i cant find a way, whatever i tried failed. I want to get the OptionsSet, the result should look something like this: 

      "LogicalName": "statuscode",
      "MetadataId": "3ac8fbd9-5b22-449b-99f5-c23b59cfe838",
      "OptionSet": {
        "MetadataId": "8ec9b368-8d0d-ea11-a811-000d3a25bbb8",
        "Options": [
          {
            "@odata.type": "#Microsoft.Dynamics.CRM.StatusOptionMetadata",
            "Value": 100000006,
            "Color": "#0000ff",
            "IsManaged": true,
            "ExternalValue": null,
            "ParentValues": [],
            "MetadataId": null,
            "HasChanged": null,
            "State": 0,
            "TransitionData": "",
            "Label": {
              "LocalizedLabels": [
                {                 "Label": "New",
                  "LanguageCode": 1033,
                  "IsManaged": true,
                  "MetadataId": "ab39f694-c74f-4ca4-af9a-994b68924b08",
                  "HasChanged": null
                },

My best attempt so far was :

`    var request1 = {
        collection: "EntityDefinitions",
        key: "LogicalName='opportunity'",
        navigationProperty: "Attributes",
        navigationPropertyKey: "LogicalName='statuscode'",
        metadataAttributeType: "Microsoft.Dynamics.CRM.StatusAttributeMetadata"
      };
let requestData = await dynamicsWebApi.retrieveRequest(request1)
`
I got the same result with 
`  let requestData = await dynamicsWebApi.retrieveAttributes(
        "LogicalName='opportunity'",
        "Microsoft.Dynamics.CRM.StatusAttributeMetadata"   );`

Unfortunately i am not able to go further from there. I  I basically stuck to do the "$select=LogicalName&$expand=OptionSet($select=Options)" part of the query above.

Is this feature not supported, or is it just me?

Help would be highly appreciated!
Thanks and regards

MrMoehner

**Comment by AleksandrRogov** [comment]
Hi @MrMoehner ,

Please try the following:

```js
let result = await dynamicsWebApi.retrieveAttributes(
    "LogicalName='opportunity'", 
    "Microsoft.Dynamics.CRM.StatusAttributeMetadata",
    ["LogicalName"], 
    null, 
    {
        property: "OptionSet",
        select: ["Options"]
    }
);
```

Or

```js
const request = {
    collection: 'EntityDefinitions',
    key: "LogicalName='opportunity'",
    navigationProperty: 'Attributes',
    select: ["LogicalName"],
    expand: {
        property: "OptionSet",
        select: ["Options"]
    },
    metadataAttributeType: "Microsoft.Dynamics.CRM.StatusAttributeMetadata"
};

let result = await dynamicsWebApi.retrieveRequest(request);
```

Hope this helps!

**Comment by AleksandrRogov** [comment]
Also you can check this wiki link to see all the parameters for the `retrieveAttributes` function: https://github.com/AleksandrRogov/DynamicsWebApi/wiki/api-classes-dynamicswebapi#retrieveattributes

**Comment by MrMoehner** [comment]
Hello AleksandrRogov, 

thanks a lot for your support, i really appreciate it!!!
Your solution seem to be just right to me, if there was a "OptionSet" property to expand from type "Microsoft.Dynamics.CRM.StatusAttributeMetadata" in the entity "opportunity". But it isnt there, and therefore the "expand" Paramter doesnt work (according to my analysis) 

Unfortunately, there is something special, the way these "Status" Attributes are handled in Dynamics. Maybe because they related to the "State" a therefore beeing mapped with a "StatusMap".

What i actually need is to request an Attribute of type 
"Microsoft.Dynamics.CRM.StatusOptionMetadata", because these are the types of attributes i get with HTTP Request i mentioned before.
Its wired, that the HTTP request works this way nevertheless, and your examples dont. 
 
If i change "Microsoft.Dynamics.CRM.StatusAttributeMetadata" with "Microsoft.Dynamics.CRM.StatusOptionMetadata" in your example , i get the following result: 
"Error: The type 'Microsoft.Dynamics.CRM.StatusOptionMetadata' specified in the URI is neither a base type nor a sub-type of the previously-specified type 'Microsoft.Dynamics.CRM.AttributeMetadata'."

I am sure i am doing something wrong here, but i just cant wrap my head around it what it is. 

Thanks a lot again!!!

MrMoehner

**Comment by AleksandrRogov** [comment]
@MrMoehner not sure.

Here are the examples of the urls that could help you to figure out what you need to retrieve. All of it can be done in DynamicsWebApi. Let me know what url you need to use and I will help you to make a request using DynamicsWebApi.

http://crmmemories.blogspot.com/2018/05/retrieve-status-reason-metadata-with.html

Thanks

**Comment by MrMoehner** [comment]
Hello AleksandrRogov, 

thanks again for your support.
I have read exactly this blogpost already, it helped me building the URL that worked for me in the Browser. The following URL gives me exactly what i need in my System.

https://XXXXXYOURURLXXXX.dynamics.com/api/data/v9.1/EntityDefinitions(LogicalName='opportunity')/Attributes/Microsoft.Dynamics.CRM.StatusAttributeMetadata?$select=LogicalName&$expand=OptionSet($select=Options)

 
If you are able to make a similiar request using DynamicsWebApiyou are my hero! 
Looks pretty similiar to the examples you gave me already. I ruled permission problems out. 
Your examples just give me the properties of the "opportunity" back.
...
           "LinkedAttributeId": null,
            **"LogicalName": "statuscode",**
            "IsValidForForm": true,
            "IsRequiredForForm": false,
            "IsValidForGrid": true,
            **"SchemaName": "StatusCode",**
            "ExternalName": null,
            "IsLogical": false,
...

I want the attribute Values of the "statuscode" itself.

  "LogicalName": "statuscode",
  "MetadataId": "3ac8fbd9-5b22-449b-99f5-c23b59cfe838",
  "OptionSet": {
    "MetadataId": "8ec9b368-8d0d-ea11-a811-000d3a25bbb8",
    "Options": [
      {
        "@odata.type": "#Microsoft.Dynamics.CRM.StatusOptionMetadata",
        "Value": 100000006,
        "Color": "#0000ff",
        "IsManaged": true,
        "ExternalValue": null,
        "ParentValues": [],
        "MetadataId": null,
        "HasChanged": null,
        "State": 0,
        "TransitionData": "",
        "Label": {
          "LocalizedLabels": [
            {                 "Label": "New",
              "LanguageCode": 1033,
              "IsManaged": true,
              "MetadataId": "ab39f694-c74f-4ca4-af9a-994b68924b08",
              "HasChanged": null
            },

Thanks and regards

MrMoehner

**Comment by AleksandrRogov** [comment]
@MrMoehner I don't understand. I've already given you the sample that will fetch data from that URL, have I not? I am confused.

**Comment by AleksandrRogov** [comment]
@MrMoehner ah, i see the issue, it was a misstype on my part, sorry. the expand must be an array of objects, i missed an array declaration, here are the working examples:

```js

let result = await dynamicsWebApi.retrieveAttributes(
    "LogicalName='opportunity'", 
    "Microsoft.Dynamics.CRM.StatusAttributeMetadata",
    ["LogicalName"], 
    null, 
    [{
        property: "OptionSet",
        select: ["Options"]
    }]
);
```

Or

```js

const request = {
    collection: 'EntityDefinitions',
    key: "LogicalName='opportunity'",
    navigationProperty: 'Attributes',
    select: ["LogicalName"],
    expand: [{
        property: "OptionSet",
        select: ["Options"]
    }],
    metadataAttributeType: "Microsoft.Dynamics.CRM.StatusAttributeMetadata"
};

let result = await dynamicsWebApi.retrieveRequest(request);
```

**Comment by MrMoehner** [comment]
Dear AleksandrRogov, 
thank you so much for your help! That finally worked.
Since i am using "expand" already in other requests with a string, i would have never guessed to wrap them in an object. 
I really appreciate you support. The package works great anyway!!!

Best regards

MrMoehner
