### ISSUE TITLE
How to run code sample for Node version

### ISSUE THREAD

**Issue by rizkysyazuli** [AleksandrRogov/DynamicsWebApi#9]
Hi, this is my first time interacting any of this. So please consider me as a total noob.

I'm building a website for a client that requires the use of Dynamics CRM as the backend for the membership system. And they refer me to this library.

I'm trying out the `adal-node` code example in your README. But it gives me a timeout error.

I saved the example code to a `start.js`.
Udated the config with the ones my client gave me:

```js
var authorityUrl = 'https://login.microsoftonline.com/<tenant>/oauth2/token';
var resource = '<resource>'; // https://xxx.dynamics.com/
var clientId = '<client_id>';
var username = '<username>';
var password = '<password>';
```

Run it in the Terminal.

    node start.js

Then after waiting quite a while, i got this error message:

    Error: connect ETIMEDOUT xxx.xx.xxx.xx:443

So did i miss anything?

**Comment by AleksandrRogov** [comment]
Hi @rizkysyazuli ,
Please check the endpoint if it's specified correctly. And if you wish to authenticate users seamlessly you must add a Redirect URI: "urn:ietf:wg:oauth:2.0:oob" to your app registered in Azure.

I hope this helps

**Comment by rizkysyazuli** [comment]
@AleksandrRogov which endpoint? honestly, i'm not really sure with what i'm doing here. i don't have direct access to Azure or any of the platform. they only gave me a spreadsheet with a bunch of parameters and list of API endpoints. 

btw, they already have a `redirect_uri` param in that spreadsheet. should i use it somewhere in the script? or should i just ask them to add `urn:ietf:wg:oauth:2.0:oob`.

**Comment by AleksandrRogov** [comment]
@rizkysyazuli well... that's complicated then. it depends what app you need to build. and yes, this question is more to adal-node developers.

**Comment by rizkysyazuli** [comment]
@AleksandrRogov understood. i'll ask around there. thx anyway for your time. 👍

**Comment by rizkysyazuli** [comment]
@AleksandrRogov i'm back :) so I made a tiny progress. turns out the script must be run from a server with a whitelisted IP.

but now i got this error.

```
Host: localhost. is not in the cert's altnames: DNS:mydomain.id, DNS:www.mydomain.id
```

**Comment by AleksandrRogov** [comment]
Hi @rizkysyazuli ,
I guess, that means that something is wrong with the url you are trying to call. It's not reachable from the machine where you're running your application.
