### ISSUE TITLE
Dist folder not being delivered

### ISSUE THREAD

**Issue by RGnt** [AleksandrRogov/DynamicsWebApi#90]
While installing the dynamics-web-api through npm, the dist folder for web browsers version of scripts is not delivered along with the library.

**Comment by AleksandrRogov** [comment]
@RGnt I don't include it there on purpose. 
You can generate it by running `npm run build` in `dynamics-web-api` folder, therefore you can add that in a build command for your package, if it's needed.
Let me know if it helped (or not).

**Comment by RGnt** [comment]
Ok, so it was me being dumb/lazy as it used work with older versions.
