### ISSUE TITLE
Assigning records

### ISSUE THREAD

**Issue by nwoodcl** [AleksandrRogov/DynamicsWebApi#93]
Hi 
I was wondering what the best way would be to assign records to a new owner (team/user)? I could not find anything in the documentation.

**Comment by AleksandrRogov** [comment]
Hi @nwoodcl, you would need to understand how Web Api works, specifically how assigning works, it is the same for all lookups.

Example:

```js
const request = {
    key: "00000000-0000-0000-0000-000000000001",
    collection: "accounts",
    "ownerid@odata.bind": "teams(00000000-0000-0000-0000-000000000002)" 
    //or "ownerid@odata.bind": "systemusers(00000000-0000-0000-0000-000000000002)"
};

await dynamicsWebApi.updateRequest(request);
```

**Comment by nwoodcl** [comment]
Thanks @AleksandrRogov 
I tried this as per the below but I get a 405 

[org]/api/data/v9.1/incidents
UPDATE ERROR: Error: The requested resource does not support http method 'PATCH'.

Code
`var dynamicsWebApi = new DynamicsWebApi.default({ webApiVersion: '9.1' });

            const request = {
                key: props.CaseId,
                collection: "incidents",
                "ownerid@odata.bind": "systemusers(" + selUserId + ")" 
            };
            
            dynamicsWebApi.updateRequest(request).then(function () {
                console.log("UPDATE SUCCESS: ");
                window.close();
            })
            .catch(function (error) {
                console.log("UPDATE ERROR: " + error);
            });`

**Comment by AleksandrRogov** [comment]
@nwoodcl my bad, it should have been, sometimes I don't see what I am typing lol:
```js
const request = {
    key: "00000000-0000-0000-0000-000000000001",
    collection: "accounts",
    entity: {
        "ownerid@odata.bind": "teams(00000000-0000-0000-0000-000000000002)"
        //or "ownerid@odata.bind": "systemusers(00000000-0000-0000-0000-000000000002)"
    }
};

await dynamicsWebApi.updateRequest(request);
```

**Comment by nwoodcl** [comment]
Thanks @AleksandrRogov 

I have made the change to the request structure as per your update but still get the same 405 PATCH error.

The new request is now:

```
const request = {
                key: props.CaseId,
                collection: "incidents",
                entity: {
                    "ownerid@odata.bind": "systemusers(" + selUserId + ")" 
                }
            };
```

**Comment by AleksandrRogov** [comment]
@nwoodcl i don't know it does support PATCH request: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/incident?view=dynamics-ce-odata-9

**Comment by nwoodcl** [comment]
Thanks @AleksandrRogov 
I was more worried I still had the request wrong and it was a false error message due to something else.

I will continue to do some digging then to see if I can do some direct webapi calls in postman etc.

Thanks again

**Comment by AleksandrRogov** [comment]
@nwoodcl just ran a test in my org and it worked fine:

```js
let result = await dynamicsWebApi.updateRequest({
    collection: "incidents",
    key: incindent.indindentid,
    entity: {
        "ownerid@odata.bind": `systemusers(${userid})`
    }
});
```

**Comment by nwoodcl** [comment]
@AleksandrRogov Actually simple mistake on my end, the id was not from the primary record, so strange error, I would have thought I would be getting the usual "Incident with id xxx does not exist"

Thanks again for all of your help. fantastic project and very well written!

**Comment by AleksandrRogov** [comment]
I am glad you found the issue! And thank you so much for your kind words!
